// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: recontaskparameter.proto

#include "recontaskparameter.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG
namespace recontaskparameter_pb {
constexpr ReconTaskParameterPB::ReconTaskParameterPB(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)
  : sinogram_data_()
  , restored_sinogram_data_()
  , reconstructed_tomographs_data_()
  , task_name_(&::PROTOBUF_NAMESPACE_ID::internal::fixed_address_empty_string)
  , path_sysmat_(&::PROTOBUF_NAMESPACE_ID::internal::fixed_address_empty_string)
  , path_sinogdram_(&::PROTOBUF_NAMESPACE_ID::internal::fixed_address_empty_string)
  , path_scatter_map_(&::PROTOBUF_NAMESPACE_ID::internal::fixed_address_empty_string)
  , path_mu_map_(&::PROTOBUF_NAMESPACE_ID::internal::fixed_address_empty_string)
  , output_dir_(&::PROTOBUF_NAMESPACE_ID::internal::fixed_address_empty_string)
  , path_model_(&::PROTOBUF_NAMESPACE_ID::internal::fixed_address_empty_string)
  , sinogram_info_(&::PROTOBUF_NAMESPACE_ID::internal::fixed_address_empty_string)
  , num_iters_(0)
  , num_dual_iters_(0)
  , gamma_(0)
  , lambda_(0)
  , coeff_scatter_(0)
  , iterator_(0)

  , file_format_(0)

  , num_input_images_(0)
  , use_nn_(false)
  , use_scatter_map_(false)
  , done_(false)
  , loaded_(false)
  , index_sinogram_(0)
  , index_projection_(0)
  , num_detectors_(0)
  , num_angles_(0)
  , num_slices_(0)
  , num_results_(0)
  , resolution_(0)
  , file_data_type_(1)
{}
struct ReconTaskParameterPBDefaultTypeInternal {
  constexpr ReconTaskParameterPBDefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~ReconTaskParameterPBDefaultTypeInternal() {}
  union {
    ReconTaskParameterPB _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT ReconTaskParameterPBDefaultTypeInternal _ReconTaskParameterPB_default_instance_;
}  // namespace recontaskparameter_pb
static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_recontaskparameter_2eproto[1];
static const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* file_level_enum_descriptors_recontaskparameter_2eproto[3];
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_recontaskparameter_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_recontaskparameter_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  PROTOBUF_FIELD_OFFSET(::recontaskparameter_pb::ReconTaskParameterPB, _has_bits_),
  PROTOBUF_FIELD_OFFSET(::recontaskparameter_pb::ReconTaskParameterPB, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::recontaskparameter_pb::ReconTaskParameterPB, task_name_),
  PROTOBUF_FIELD_OFFSET(::recontaskparameter_pb::ReconTaskParameterPB, path_sysmat_),
  PROTOBUF_FIELD_OFFSET(::recontaskparameter_pb::ReconTaskParameterPB, path_sinogdram_),
  PROTOBUF_FIELD_OFFSET(::recontaskparameter_pb::ReconTaskParameterPB, path_scatter_map_),
  PROTOBUF_FIELD_OFFSET(::recontaskparameter_pb::ReconTaskParameterPB, path_mu_map_),
  PROTOBUF_FIELD_OFFSET(::recontaskparameter_pb::ReconTaskParameterPB, use_nn_),
  PROTOBUF_FIELD_OFFSET(::recontaskparameter_pb::ReconTaskParameterPB, use_scatter_map_),
  PROTOBUF_FIELD_OFFSET(::recontaskparameter_pb::ReconTaskParameterPB, num_iters_),
  PROTOBUF_FIELD_OFFSET(::recontaskparameter_pb::ReconTaskParameterPB, num_dual_iters_),
  PROTOBUF_FIELD_OFFSET(::recontaskparameter_pb::ReconTaskParameterPB, gamma_),
  PROTOBUF_FIELD_OFFSET(::recontaskparameter_pb::ReconTaskParameterPB, lambda_),
  PROTOBUF_FIELD_OFFSET(::recontaskparameter_pb::ReconTaskParameterPB, coeff_scatter_),
  PROTOBUF_FIELD_OFFSET(::recontaskparameter_pb::ReconTaskParameterPB, output_dir_),
  PROTOBUF_FIELD_OFFSET(::recontaskparameter_pb::ReconTaskParameterPB, iterator_),
  PROTOBUF_FIELD_OFFSET(::recontaskparameter_pb::ReconTaskParameterPB, file_format_),
  PROTOBUF_FIELD_OFFSET(::recontaskparameter_pb::ReconTaskParameterPB, num_input_images_),
  PROTOBUF_FIELD_OFFSET(::recontaskparameter_pb::ReconTaskParameterPB, file_data_type_),
  PROTOBUF_FIELD_OFFSET(::recontaskparameter_pb::ReconTaskParameterPB, index_sinogram_),
  PROTOBUF_FIELD_OFFSET(::recontaskparameter_pb::ReconTaskParameterPB, index_projection_),
  PROTOBUF_FIELD_OFFSET(::recontaskparameter_pb::ReconTaskParameterPB, num_detectors_),
  PROTOBUF_FIELD_OFFSET(::recontaskparameter_pb::ReconTaskParameterPB, num_angles_),
  PROTOBUF_FIELD_OFFSET(::recontaskparameter_pb::ReconTaskParameterPB, num_slices_),
  PROTOBUF_FIELD_OFFSET(::recontaskparameter_pb::ReconTaskParameterPB, num_results_),
  PROTOBUF_FIELD_OFFSET(::recontaskparameter_pb::ReconTaskParameterPB, sinogram_data_),
  PROTOBUF_FIELD_OFFSET(::recontaskparameter_pb::ReconTaskParameterPB, restored_sinogram_data_),
  PROTOBUF_FIELD_OFFSET(::recontaskparameter_pb::ReconTaskParameterPB, reconstructed_tomographs_data_),
  PROTOBUF_FIELD_OFFSET(::recontaskparameter_pb::ReconTaskParameterPB, done_),
  PROTOBUF_FIELD_OFFSET(::recontaskparameter_pb::ReconTaskParameterPB, loaded_),
  PROTOBUF_FIELD_OFFSET(::recontaskparameter_pb::ReconTaskParameterPB, path_model_),
  PROTOBUF_FIELD_OFFSET(::recontaskparameter_pb::ReconTaskParameterPB, sinogram_info_),
  PROTOBUF_FIELD_OFFSET(::recontaskparameter_pb::ReconTaskParameterPB, resolution_),
  0,
  1,
  2,
  3,
  4,
  16,
  17,
  8,
  9,
  10,
  11,
  12,
  5,
  13,
  14,
  15,
  27,
  20,
  21,
  22,
  23,
  24,
  25,
  ~0u,
  ~0u,
  ~0u,
  18,
  19,
  6,
  7,
  26,
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 36, sizeof(::recontaskparameter_pb::ReconTaskParameterPB)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::recontaskparameter_pb::_ReconTaskParameterPB_default_instance_),
};

const char descriptor_table_protodef_recontaskparameter_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\030recontaskparameter.proto\022\025recontaskpar"
  "ameter_pb\"\304\t\n\024ReconTaskParameterPB\022\021\n\tta"
  "sk_name\030\001 \002(\t\022\023\n\013path_sysmat\030\002 \002(\t\022\026\n\016pa"
  "th_sinogdram\030\003 \002(\t\022\030\n\020path_scatter_map\030\004"
  " \001(\t\022\023\n\013path_mu_map\030\005 \001(\t\022\016\n\006use_nn\030\006 \002("
  "\010\022\027\n\017use_scatter_map\030\007 \002(\010\022\021\n\tnum_iters\030"
  "\010 \002(\005\022\026\n\016num_dual_iters\030\t \002(\005\022\r\n\005gamma\030\n"
  " \002(\001\022\016\n\006lambda\030\013 \002(\001\022\025\n\rcoeff_scatter\030\014 "
  "\001(\001\022\022\n\noutput_dir\030\r \002(\t\022J\n\010iterator\030\016 \002("
  "\01628.recontaskparameter_pb.ReconTaskParam"
  "eterPB.IteratorType\022K\n\013file_format\030\017 \002(\016"
  "26.recontaskparameter_pb.ReconTaskParame"
  "terPB.FileFormat\022\030\n\020num_input_images\030\020 \002"
  "(\005\022P\n\016file_data_type\030\021 \002(\01628.recontaskpa"
  "rameter_pb.ReconTaskParameterPB.FileData"
  "Type\022\026\n\016index_sinogram\030\022 \002(\005\022\030\n\020index_pr"
  "ojection\030\023 \002(\005\022\025\n\rnum_detectors\030\024 \002(\005\022\022\n"
  "\nnum_angles\030\025 \002(\005\022\022\n\nnum_slices\030\026 \002(\005\022\023\n"
  "\013num_results\030\027 \002(\005\022\025\n\rsinogram_data\030\030 \003("
  "\001\022\036\n\026restored_sinogram_data\030\031 \003(\001\022%\n\035rec"
  "onstructed_tomographs_data\030\032 \003(\001\022\014\n\004done"
  "\030\033 \002(\010\022\016\n\006loaded\030\034 \002(\010\022\022\n\npath_model\030\035 \002"
  "(\t\022\025\n\rsinogram_info\030\036 \002(\t\022\022\n\nresolution\030"
  "\037 \002(\005\"\224\001\n\014IteratorType\022\010\n\004MLEM\020\000\022\017\n\013EM_T"
  "ikhonov\020\001\022\022\n\016PAPA_2DWavelet\020\002\022\r\n\tPAPA_Co"
  "nt\020\003\022\020\n\014PAPA_Cont_TV\020\004\022\025\n\021PAPA_Cont_Wave"
  "let\020\005\022\020\n\014PAPA_Dynamic\020\006\022\013\n\007PAPA_TV\020\007\"=\n\n"
  "FileFormat\022\020\n\014RAW_SINOGRAM\020\000\022\022\n\016RAW_PROJ"
  "ECTION\020\001\022\t\n\005DICOM\020\002\"\202\001\n\014FileDataType\022\013\n\007"
  "FLOAT32\020\001\022\013\n\007FLOAT64\020\002\022\010\n\004INT8\020\003\022\t\n\005UINT"
  "8\020\004\022\t\n\005INT16\020\005\022\n\n\006UINT16\020\006\022\t\n\005INT32\020\007\022\n\n"
  "\006UINT32\020\010\022\t\n\005INT64\020\t\022\n\n\006UINT64\020\n"
  ;
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_recontaskparameter_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_recontaskparameter_2eproto = {
  false, false, 1272, descriptor_table_protodef_recontaskparameter_2eproto, "recontaskparameter.proto", 
  &descriptor_table_recontaskparameter_2eproto_once, nullptr, 0, 1,
  schemas, file_default_instances, TableStruct_recontaskparameter_2eproto::offsets,
  file_level_metadata_recontaskparameter_2eproto, file_level_enum_descriptors_recontaskparameter_2eproto, file_level_service_descriptors_recontaskparameter_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable* descriptor_table_recontaskparameter_2eproto_getter() {
  return &descriptor_table_recontaskparameter_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY static ::PROTOBUF_NAMESPACE_ID::internal::AddDescriptorsRunner dynamic_init_dummy_recontaskparameter_2eproto(&descriptor_table_recontaskparameter_2eproto);
namespace recontaskparameter_pb {
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ReconTaskParameterPB_IteratorType_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_recontaskparameter_2eproto);
  return file_level_enum_descriptors_recontaskparameter_2eproto[0];
}
bool ReconTaskParameterPB_IteratorType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
    case 7:
      return true;
    default:
      return false;
  }
}

#if (__cplusplus < 201703) && (!defined(_MSC_VER) || _MSC_VER >= 1900)
constexpr ReconTaskParameterPB_IteratorType ReconTaskParameterPB::MLEM;
constexpr ReconTaskParameterPB_IteratorType ReconTaskParameterPB::EM_Tikhonov;
constexpr ReconTaskParameterPB_IteratorType ReconTaskParameterPB::PAPA_2DWavelet;
constexpr ReconTaskParameterPB_IteratorType ReconTaskParameterPB::PAPA_Cont;
constexpr ReconTaskParameterPB_IteratorType ReconTaskParameterPB::PAPA_Cont_TV;
constexpr ReconTaskParameterPB_IteratorType ReconTaskParameterPB::PAPA_Cont_Wavelet;
constexpr ReconTaskParameterPB_IteratorType ReconTaskParameterPB::PAPA_Dynamic;
constexpr ReconTaskParameterPB_IteratorType ReconTaskParameterPB::PAPA_TV;
constexpr ReconTaskParameterPB_IteratorType ReconTaskParameterPB::IteratorType_MIN;
constexpr ReconTaskParameterPB_IteratorType ReconTaskParameterPB::IteratorType_MAX;
constexpr int ReconTaskParameterPB::IteratorType_ARRAYSIZE;
#endif  // (__cplusplus < 201703) && (!defined(_MSC_VER) || _MSC_VER >= 1900)
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ReconTaskParameterPB_FileFormat_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_recontaskparameter_2eproto);
  return file_level_enum_descriptors_recontaskparameter_2eproto[1];
}
bool ReconTaskParameterPB_FileFormat_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}

#if (__cplusplus < 201703) && (!defined(_MSC_VER) || _MSC_VER >= 1900)
constexpr ReconTaskParameterPB_FileFormat ReconTaskParameterPB::RAW_SINOGRAM;
constexpr ReconTaskParameterPB_FileFormat ReconTaskParameterPB::RAW_PROJECTION;
constexpr ReconTaskParameterPB_FileFormat ReconTaskParameterPB::DICOM;
constexpr ReconTaskParameterPB_FileFormat ReconTaskParameterPB::FileFormat_MIN;
constexpr ReconTaskParameterPB_FileFormat ReconTaskParameterPB::FileFormat_MAX;
constexpr int ReconTaskParameterPB::FileFormat_ARRAYSIZE;
#endif  // (__cplusplus < 201703) && (!defined(_MSC_VER) || _MSC_VER >= 1900)
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ReconTaskParameterPB_FileDataType_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_recontaskparameter_2eproto);
  return file_level_enum_descriptors_recontaskparameter_2eproto[2];
}
bool ReconTaskParameterPB_FileDataType_IsValid(int value) {
  switch (value) {
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
    case 7:
    case 8:
    case 9:
    case 10:
      return true;
    default:
      return false;
  }
}

#if (__cplusplus < 201703) && (!defined(_MSC_VER) || _MSC_VER >= 1900)
constexpr ReconTaskParameterPB_FileDataType ReconTaskParameterPB::FLOAT32;
constexpr ReconTaskParameterPB_FileDataType ReconTaskParameterPB::FLOAT64;
constexpr ReconTaskParameterPB_FileDataType ReconTaskParameterPB::INT8;
constexpr ReconTaskParameterPB_FileDataType ReconTaskParameterPB::UINT8;
constexpr ReconTaskParameterPB_FileDataType ReconTaskParameterPB::INT16;
constexpr ReconTaskParameterPB_FileDataType ReconTaskParameterPB::UINT16;
constexpr ReconTaskParameterPB_FileDataType ReconTaskParameterPB::INT32;
constexpr ReconTaskParameterPB_FileDataType ReconTaskParameterPB::UINT32;
constexpr ReconTaskParameterPB_FileDataType ReconTaskParameterPB::INT64;
constexpr ReconTaskParameterPB_FileDataType ReconTaskParameterPB::UINT64;
constexpr ReconTaskParameterPB_FileDataType ReconTaskParameterPB::FileDataType_MIN;
constexpr ReconTaskParameterPB_FileDataType ReconTaskParameterPB::FileDataType_MAX;
constexpr int ReconTaskParameterPB::FileDataType_ARRAYSIZE;
#endif  // (__cplusplus < 201703) && (!defined(_MSC_VER) || _MSC_VER >= 1900)

// ===================================================================

class ReconTaskParameterPB::_Internal {
 public:
  using HasBits = decltype(std::declval<ReconTaskParameterPB>()._has_bits_);
  static void set_has_task_name(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static void set_has_path_sysmat(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
  static void set_has_path_sinogdram(HasBits* has_bits) {
    (*has_bits)[0] |= 4u;
  }
  static void set_has_path_scatter_map(HasBits* has_bits) {
    (*has_bits)[0] |= 8u;
  }
  static void set_has_path_mu_map(HasBits* has_bits) {
    (*has_bits)[0] |= 16u;
  }
  static void set_has_use_nn(HasBits* has_bits) {
    (*has_bits)[0] |= 65536u;
  }
  static void set_has_use_scatter_map(HasBits* has_bits) {
    (*has_bits)[0] |= 131072u;
  }
  static void set_has_num_iters(HasBits* has_bits) {
    (*has_bits)[0] |= 256u;
  }
  static void set_has_num_dual_iters(HasBits* has_bits) {
    (*has_bits)[0] |= 512u;
  }
  static void set_has_gamma(HasBits* has_bits) {
    (*has_bits)[0] |= 1024u;
  }
  static void set_has_lambda(HasBits* has_bits) {
    (*has_bits)[0] |= 2048u;
  }
  static void set_has_coeff_scatter(HasBits* has_bits) {
    (*has_bits)[0] |= 4096u;
  }
  static void set_has_output_dir(HasBits* has_bits) {
    (*has_bits)[0] |= 32u;
  }
  static void set_has_iterator(HasBits* has_bits) {
    (*has_bits)[0] |= 8192u;
  }
  static void set_has_file_format(HasBits* has_bits) {
    (*has_bits)[0] |= 16384u;
  }
  static void set_has_num_input_images(HasBits* has_bits) {
    (*has_bits)[0] |= 32768u;
  }
  static void set_has_file_data_type(HasBits* has_bits) {
    (*has_bits)[0] |= 134217728u;
  }
  static void set_has_index_sinogram(HasBits* has_bits) {
    (*has_bits)[0] |= 1048576u;
  }
  static void set_has_index_projection(HasBits* has_bits) {
    (*has_bits)[0] |= 2097152u;
  }
  static void set_has_num_detectors(HasBits* has_bits) {
    (*has_bits)[0] |= 4194304u;
  }
  static void set_has_num_angles(HasBits* has_bits) {
    (*has_bits)[0] |= 8388608u;
  }
  static void set_has_num_slices(HasBits* has_bits) {
    (*has_bits)[0] |= 16777216u;
  }
  static void set_has_num_results(HasBits* has_bits) {
    (*has_bits)[0] |= 33554432u;
  }
  static void set_has_done(HasBits* has_bits) {
    (*has_bits)[0] |= 262144u;
  }
  static void set_has_loaded(HasBits* has_bits) {
    (*has_bits)[0] |= 524288u;
  }
  static void set_has_path_model(HasBits* has_bits) {
    (*has_bits)[0] |= 64u;
  }
  static void set_has_sinogram_info(HasBits* has_bits) {
    (*has_bits)[0] |= 128u;
  }
  static void set_has_resolution(HasBits* has_bits) {
    (*has_bits)[0] |= 67108864u;
  }
  static bool MissingRequiredFields(const HasBits& has_bits) {
    return ((has_bits[0] & 0x0fffefe7) ^ 0x0fffefe7) != 0;
  }
};

ReconTaskParameterPB::ReconTaskParameterPB(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena),
  sinogram_data_(arena),
  restored_sinogram_data_(arena),
  reconstructed_tomographs_data_(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:recontaskparameter_pb.ReconTaskParameterPB)
}
ReconTaskParameterPB::ReconTaskParameterPB(const ReconTaskParameterPB& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _has_bits_(from._has_bits_),
      sinogram_data_(from.sinogram_data_),
      restored_sinogram_data_(from.restored_sinogram_data_),
      reconstructed_tomographs_data_(from.reconstructed_tomographs_data_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  task_name_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (from._internal_has_task_name()) {
    task_name_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_task_name(), 
      GetArenaForAllocation());
  }
  path_sysmat_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (from._internal_has_path_sysmat()) {
    path_sysmat_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_path_sysmat(), 
      GetArenaForAllocation());
  }
  path_sinogdram_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (from._internal_has_path_sinogdram()) {
    path_sinogdram_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_path_sinogdram(), 
      GetArenaForAllocation());
  }
  path_scatter_map_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (from._internal_has_path_scatter_map()) {
    path_scatter_map_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_path_scatter_map(), 
      GetArenaForAllocation());
  }
  path_mu_map_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (from._internal_has_path_mu_map()) {
    path_mu_map_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_path_mu_map(), 
      GetArenaForAllocation());
  }
  output_dir_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (from._internal_has_output_dir()) {
    output_dir_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_output_dir(), 
      GetArenaForAllocation());
  }
  path_model_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (from._internal_has_path_model()) {
    path_model_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_path_model(), 
      GetArenaForAllocation());
  }
  sinogram_info_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (from._internal_has_sinogram_info()) {
    sinogram_info_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_sinogram_info(), 
      GetArenaForAllocation());
  }
  ::memcpy(&num_iters_, &from.num_iters_,
    static_cast<size_t>(reinterpret_cast<char*>(&file_data_type_) -
    reinterpret_cast<char*>(&num_iters_)) + sizeof(file_data_type_));
  // @@protoc_insertion_point(copy_constructor:recontaskparameter_pb.ReconTaskParameterPB)
}

void ReconTaskParameterPB::SharedCtor() {
task_name_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
path_sysmat_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
path_sinogdram_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
path_scatter_map_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
path_mu_map_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
output_dir_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
path_model_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
sinogram_info_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
::memset(reinterpret_cast<char*>(this) + static_cast<size_t>(
    reinterpret_cast<char*>(&num_iters_) - reinterpret_cast<char*>(this)),
    0, static_cast<size_t>(reinterpret_cast<char*>(&resolution_) -
    reinterpret_cast<char*>(&num_iters_)) + sizeof(resolution_));
file_data_type_ = 1;
}

ReconTaskParameterPB::~ReconTaskParameterPB() {
  // @@protoc_insertion_point(destructor:recontaskparameter_pb.ReconTaskParameterPB)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void ReconTaskParameterPB::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  task_name_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  path_sysmat_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  path_sinogdram_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  path_scatter_map_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  path_mu_map_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  output_dir_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  path_model_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  sinogram_info_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void ReconTaskParameterPB::ArenaDtor(void* object) {
  ReconTaskParameterPB* _this = reinterpret_cast< ReconTaskParameterPB* >(object);
  (void)_this;
}
void ReconTaskParameterPB::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void ReconTaskParameterPB::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void ReconTaskParameterPB::Clear() {
// @@protoc_insertion_point(message_clear_start:recontaskparameter_pb.ReconTaskParameterPB)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  sinogram_data_.Clear();
  restored_sinogram_data_.Clear();
  reconstructed_tomographs_data_.Clear();
  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x000000ffu) {
    if (cached_has_bits & 0x00000001u) {
      task_name_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000002u) {
      path_sysmat_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000004u) {
      path_sinogdram_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000008u) {
      path_scatter_map_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000010u) {
      path_mu_map_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000020u) {
      output_dir_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000040u) {
      path_model_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000080u) {
      sinogram_info_.ClearNonDefaultToEmpty();
    }
  }
  if (cached_has_bits & 0x0000ff00u) {
    ::memset(&num_iters_, 0, static_cast<size_t>(
        reinterpret_cast<char*>(&num_input_images_) -
        reinterpret_cast<char*>(&num_iters_)) + sizeof(num_input_images_));
  }
  if (cached_has_bits & 0x00ff0000u) {
    ::memset(&use_nn_, 0, static_cast<size_t>(
        reinterpret_cast<char*>(&num_angles_) -
        reinterpret_cast<char*>(&use_nn_)) + sizeof(num_angles_));
  }
  if (cached_has_bits & 0x0f000000u) {
    ::memset(&num_slices_, 0, static_cast<size_t>(
        reinterpret_cast<char*>(&resolution_) -
        reinterpret_cast<char*>(&num_slices_)) + sizeof(resolution_));
    file_data_type_ = 1;
  }
  _has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* ReconTaskParameterPB::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // required string task_name = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          auto str = _internal_mutable_task_name();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          #ifndef NDEBUG
          ::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "recontaskparameter_pb.ReconTaskParameterPB.task_name");
          #endif  // !NDEBUG
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // required string path_sysmat = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18)) {
          auto str = _internal_mutable_path_sysmat();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          #ifndef NDEBUG
          ::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "recontaskparameter_pb.ReconTaskParameterPB.path_sysmat");
          #endif  // !NDEBUG
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // required string path_sinogdram = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 26)) {
          auto str = _internal_mutable_path_sinogdram();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          #ifndef NDEBUG
          ::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "recontaskparameter_pb.ReconTaskParameterPB.path_sinogdram");
          #endif  // !NDEBUG
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // optional string path_scatter_map = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 34)) {
          auto str = _internal_mutable_path_scatter_map();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          #ifndef NDEBUG
          ::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "recontaskparameter_pb.ReconTaskParameterPB.path_scatter_map");
          #endif  // !NDEBUG
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // optional string path_mu_map = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 42)) {
          auto str = _internal_mutable_path_mu_map();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          #ifndef NDEBUG
          ::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "recontaskparameter_pb.ReconTaskParameterPB.path_mu_map");
          #endif  // !NDEBUG
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // required bool use_nn = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 48)) {
          _Internal::set_has_use_nn(&has_bits);
          use_nn_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // required bool use_scatter_map = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 56)) {
          _Internal::set_has_use_scatter_map(&has_bits);
          use_scatter_map_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // required int32 num_iters = 8;
      case 8:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 64)) {
          _Internal::set_has_num_iters(&has_bits);
          num_iters_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // required int32 num_dual_iters = 9;
      case 9:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 72)) {
          _Internal::set_has_num_dual_iters(&has_bits);
          num_dual_iters_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // required double gamma = 10;
      case 10:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 81)) {
          _Internal::set_has_gamma(&has_bits);
          gamma_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else goto handle_unusual;
        continue;
      // required double lambda = 11;
      case 11:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 89)) {
          _Internal::set_has_lambda(&has_bits);
          lambda_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else goto handle_unusual;
        continue;
      // optional double coeff_scatter = 12;
      case 12:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 97)) {
          _Internal::set_has_coeff_scatter(&has_bits);
          coeff_scatter_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else goto handle_unusual;
        continue;
      // required string output_dir = 13;
      case 13:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 106)) {
          auto str = _internal_mutable_output_dir();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          #ifndef NDEBUG
          ::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "recontaskparameter_pb.ReconTaskParameterPB.output_dir");
          #endif  // !NDEBUG
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // required .recontaskparameter_pb.ReconTaskParameterPB.IteratorType iterator = 14;
      case 14:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 112)) {
          ::PROTOBUF_NAMESPACE_ID::uint64 val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          if (PROTOBUF_PREDICT_TRUE(::recontaskparameter_pb::ReconTaskParameterPB_IteratorType_IsValid(val))) {
            _internal_set_iterator(static_cast<::recontaskparameter_pb::ReconTaskParameterPB_IteratorType>(val));
          } else {
            ::PROTOBUF_NAMESPACE_ID::internal::WriteVarint(14, val, mutable_unknown_fields());
          }
        } else goto handle_unusual;
        continue;
      // required .recontaskparameter_pb.ReconTaskParameterPB.FileFormat file_format = 15;
      case 15:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 120)) {
          ::PROTOBUF_NAMESPACE_ID::uint64 val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          if (PROTOBUF_PREDICT_TRUE(::recontaskparameter_pb::ReconTaskParameterPB_FileFormat_IsValid(val))) {
            _internal_set_file_format(static_cast<::recontaskparameter_pb::ReconTaskParameterPB_FileFormat>(val));
          } else {
            ::PROTOBUF_NAMESPACE_ID::internal::WriteVarint(15, val, mutable_unknown_fields());
          }
        } else goto handle_unusual;
        continue;
      // required int32 num_input_images = 16;
      case 16:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 128)) {
          _Internal::set_has_num_input_images(&has_bits);
          num_input_images_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // required .recontaskparameter_pb.ReconTaskParameterPB.FileDataType file_data_type = 17;
      case 17:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 136)) {
          ::PROTOBUF_NAMESPACE_ID::uint64 val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          if (PROTOBUF_PREDICT_TRUE(::recontaskparameter_pb::ReconTaskParameterPB_FileDataType_IsValid(val))) {
            _internal_set_file_data_type(static_cast<::recontaskparameter_pb::ReconTaskParameterPB_FileDataType>(val));
          } else {
            ::PROTOBUF_NAMESPACE_ID::internal::WriteVarint(17, val, mutable_unknown_fields());
          }
        } else goto handle_unusual;
        continue;
      // required int32 index_sinogram = 18;
      case 18:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 144)) {
          _Internal::set_has_index_sinogram(&has_bits);
          index_sinogram_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // required int32 index_projection = 19;
      case 19:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 152)) {
          _Internal::set_has_index_projection(&has_bits);
          index_projection_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // required int32 num_detectors = 20;
      case 20:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 160)) {
          _Internal::set_has_num_detectors(&has_bits);
          num_detectors_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // required int32 num_angles = 21;
      case 21:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 168)) {
          _Internal::set_has_num_angles(&has_bits);
          num_angles_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // required int32 num_slices = 22;
      case 22:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 176)) {
          _Internal::set_has_num_slices(&has_bits);
          num_slices_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // required int32 num_results = 23;
      case 23:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 184)) {
          _Internal::set_has_num_results(&has_bits);
          num_results_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // repeated double sinogram_data = 24;
      case 24:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 193)) {
          ptr -= 2;
          do {
            ptr += 2;
            _internal_add_sinogram_data(::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr));
            ptr += sizeof(double);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<193>(ptr));
        } else if (static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 194) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedDoubleParser(_internal_mutable_sinogram_data(), ptr, ctx);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // repeated double restored_sinogram_data = 25;
      case 25:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 201)) {
          ptr -= 2;
          do {
            ptr += 2;
            _internal_add_restored_sinogram_data(::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr));
            ptr += sizeof(double);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<201>(ptr));
        } else if (static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 202) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedDoubleParser(_internal_mutable_restored_sinogram_data(), ptr, ctx);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // repeated double reconstructed_tomographs_data = 26;
      case 26:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 209)) {
          ptr -= 2;
          do {
            ptr += 2;
            _internal_add_reconstructed_tomographs_data(::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr));
            ptr += sizeof(double);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<209>(ptr));
        } else if (static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 210) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedDoubleParser(_internal_mutable_reconstructed_tomographs_data(), ptr, ctx);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // required bool done = 27;
      case 27:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 216)) {
          _Internal::set_has_done(&has_bits);
          done_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // required bool loaded = 28;
      case 28:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 224)) {
          _Internal::set_has_loaded(&has_bits);
          loaded_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // required string path_model = 29;
      case 29:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 234)) {
          auto str = _internal_mutable_path_model();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          #ifndef NDEBUG
          ::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "recontaskparameter_pb.ReconTaskParameterPB.path_model");
          #endif  // !NDEBUG
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // required string sinogram_info = 30;
      case 30:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 242)) {
          auto str = _internal_mutable_sinogram_info();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          #ifndef NDEBUG
          ::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "recontaskparameter_pb.ReconTaskParameterPB.sinogram_info");
          #endif  // !NDEBUG
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // required int32 resolution = 31;
      case 31:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 248)) {
          _Internal::set_has_resolution(&has_bits);
          resolution_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag == 0) || ((tag & 7) == 4)) {
          CHK_(ptr);
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  _has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* ReconTaskParameterPB::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:recontaskparameter_pb.ReconTaskParameterPB)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // required string task_name = 1;
  if (cached_has_bits & 0x00000001u) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::VerifyUTF8StringNamedField(
      this->_internal_task_name().data(), static_cast<int>(this->_internal_task_name().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::SERIALIZE,
      "recontaskparameter_pb.ReconTaskParameterPB.task_name");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_task_name(), target);
  }

  // required string path_sysmat = 2;
  if (cached_has_bits & 0x00000002u) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::VerifyUTF8StringNamedField(
      this->_internal_path_sysmat().data(), static_cast<int>(this->_internal_path_sysmat().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::SERIALIZE,
      "recontaskparameter_pb.ReconTaskParameterPB.path_sysmat");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_path_sysmat(), target);
  }

  // required string path_sinogdram = 3;
  if (cached_has_bits & 0x00000004u) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::VerifyUTF8StringNamedField(
      this->_internal_path_sinogdram().data(), static_cast<int>(this->_internal_path_sinogdram().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::SERIALIZE,
      "recontaskparameter_pb.ReconTaskParameterPB.path_sinogdram");
    target = stream->WriteStringMaybeAliased(
        3, this->_internal_path_sinogdram(), target);
  }

  // optional string path_scatter_map = 4;
  if (cached_has_bits & 0x00000008u) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::VerifyUTF8StringNamedField(
      this->_internal_path_scatter_map().data(), static_cast<int>(this->_internal_path_scatter_map().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::SERIALIZE,
      "recontaskparameter_pb.ReconTaskParameterPB.path_scatter_map");
    target = stream->WriteStringMaybeAliased(
        4, this->_internal_path_scatter_map(), target);
  }

  // optional string path_mu_map = 5;
  if (cached_has_bits & 0x00000010u) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::VerifyUTF8StringNamedField(
      this->_internal_path_mu_map().data(), static_cast<int>(this->_internal_path_mu_map().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::SERIALIZE,
      "recontaskparameter_pb.ReconTaskParameterPB.path_mu_map");
    target = stream->WriteStringMaybeAliased(
        5, this->_internal_path_mu_map(), target);
  }

  // required bool use_nn = 6;
  if (cached_has_bits & 0x00010000u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteBoolToArray(6, this->_internal_use_nn(), target);
  }

  // required bool use_scatter_map = 7;
  if (cached_has_bits & 0x00020000u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteBoolToArray(7, this->_internal_use_scatter_map(), target);
  }

  // required int32 num_iters = 8;
  if (cached_has_bits & 0x00000100u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(8, this->_internal_num_iters(), target);
  }

  // required int32 num_dual_iters = 9;
  if (cached_has_bits & 0x00000200u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(9, this->_internal_num_dual_iters(), target);
  }

  // required double gamma = 10;
  if (cached_has_bits & 0x00000400u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteDoubleToArray(10, this->_internal_gamma(), target);
  }

  // required double lambda = 11;
  if (cached_has_bits & 0x00000800u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteDoubleToArray(11, this->_internal_lambda(), target);
  }

  // optional double coeff_scatter = 12;
  if (cached_has_bits & 0x00001000u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteDoubleToArray(12, this->_internal_coeff_scatter(), target);
  }

  // required string output_dir = 13;
  if (cached_has_bits & 0x00000020u) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::VerifyUTF8StringNamedField(
      this->_internal_output_dir().data(), static_cast<int>(this->_internal_output_dir().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::SERIALIZE,
      "recontaskparameter_pb.ReconTaskParameterPB.output_dir");
    target = stream->WriteStringMaybeAliased(
        13, this->_internal_output_dir(), target);
  }

  // required .recontaskparameter_pb.ReconTaskParameterPB.IteratorType iterator = 14;
  if (cached_has_bits & 0x00002000u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteEnumToArray(
      14, this->_internal_iterator(), target);
  }

  // required .recontaskparameter_pb.ReconTaskParameterPB.FileFormat file_format = 15;
  if (cached_has_bits & 0x00004000u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteEnumToArray(
      15, this->_internal_file_format(), target);
  }

  // required int32 num_input_images = 16;
  if (cached_has_bits & 0x00008000u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(16, this->_internal_num_input_images(), target);
  }

  // required .recontaskparameter_pb.ReconTaskParameterPB.FileDataType file_data_type = 17;
  if (cached_has_bits & 0x08000000u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteEnumToArray(
      17, this->_internal_file_data_type(), target);
  }

  // required int32 index_sinogram = 18;
  if (cached_has_bits & 0x00100000u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(18, this->_internal_index_sinogram(), target);
  }

  // required int32 index_projection = 19;
  if (cached_has_bits & 0x00200000u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(19, this->_internal_index_projection(), target);
  }

  // required int32 num_detectors = 20;
  if (cached_has_bits & 0x00400000u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(20, this->_internal_num_detectors(), target);
  }

  // required int32 num_angles = 21;
  if (cached_has_bits & 0x00800000u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(21, this->_internal_num_angles(), target);
  }

  // required int32 num_slices = 22;
  if (cached_has_bits & 0x01000000u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(22, this->_internal_num_slices(), target);
  }

  // required int32 num_results = 23;
  if (cached_has_bits & 0x02000000u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(23, this->_internal_num_results(), target);
  }

  // repeated double sinogram_data = 24;
  for (int i = 0, n = this->_internal_sinogram_data_size(); i < n; i++) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteDoubleToArray(24, this->_internal_sinogram_data(i), target);
  }

  // repeated double restored_sinogram_data = 25;
  for (int i = 0, n = this->_internal_restored_sinogram_data_size(); i < n; i++) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteDoubleToArray(25, this->_internal_restored_sinogram_data(i), target);
  }

  // repeated double reconstructed_tomographs_data = 26;
  for (int i = 0, n = this->_internal_reconstructed_tomographs_data_size(); i < n; i++) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteDoubleToArray(26, this->_internal_reconstructed_tomographs_data(i), target);
  }

  // required bool done = 27;
  if (cached_has_bits & 0x00040000u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteBoolToArray(27, this->_internal_done(), target);
  }

  // required bool loaded = 28;
  if (cached_has_bits & 0x00080000u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteBoolToArray(28, this->_internal_loaded(), target);
  }

  // required string path_model = 29;
  if (cached_has_bits & 0x00000040u) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::VerifyUTF8StringNamedField(
      this->_internal_path_model().data(), static_cast<int>(this->_internal_path_model().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::SERIALIZE,
      "recontaskparameter_pb.ReconTaskParameterPB.path_model");
    target = stream->WriteStringMaybeAliased(
        29, this->_internal_path_model(), target);
  }

  // required string sinogram_info = 30;
  if (cached_has_bits & 0x00000080u) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::VerifyUTF8StringNamedField(
      this->_internal_sinogram_info().data(), static_cast<int>(this->_internal_sinogram_info().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::SERIALIZE,
      "recontaskparameter_pb.ReconTaskParameterPB.sinogram_info");
    target = stream->WriteStringMaybeAliased(
        30, this->_internal_sinogram_info(), target);
  }

  // required int32 resolution = 31;
  if (cached_has_bits & 0x04000000u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(31, this->_internal_resolution(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:recontaskparameter_pb.ReconTaskParameterPB)
  return target;
}

size_t ReconTaskParameterPB::RequiredFieldsByteSizeFallback() const {
// @@protoc_insertion_point(required_fields_byte_size_fallback_start:recontaskparameter_pb.ReconTaskParameterPB)
  size_t total_size = 0;

  if (_internal_has_task_name()) {
    // required string task_name = 1;
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_task_name());
  }

  if (_internal_has_path_sysmat()) {
    // required string path_sysmat = 2;
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_path_sysmat());
  }

  if (_internal_has_path_sinogdram()) {
    // required string path_sinogdram = 3;
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_path_sinogdram());
  }

  if (_internal_has_output_dir()) {
    // required string output_dir = 13;
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_output_dir());
  }

  if (_internal_has_path_model()) {
    // required string path_model = 29;
    total_size += 2 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_path_model());
  }

  if (_internal_has_sinogram_info()) {
    // required string sinogram_info = 30;
    total_size += 2 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_sinogram_info());
  }

  if (_internal_has_num_iters()) {
    // required int32 num_iters = 8;
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
        this->_internal_num_iters());
  }

  if (_internal_has_num_dual_iters()) {
    // required int32 num_dual_iters = 9;
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
        this->_internal_num_dual_iters());
  }

  if (_internal_has_gamma()) {
    // required double gamma = 10;
    total_size += 1 + 8;
  }

  if (_internal_has_lambda()) {
    // required double lambda = 11;
    total_size += 1 + 8;
  }

  if (_internal_has_iterator()) {
    // required .recontaskparameter_pb.ReconTaskParameterPB.IteratorType iterator = 14;
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::EnumSize(this->_internal_iterator());
  }

  if (_internal_has_file_format()) {
    // required .recontaskparameter_pb.ReconTaskParameterPB.FileFormat file_format = 15;
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::EnumSize(this->_internal_file_format());
  }

  if (_internal_has_num_input_images()) {
    // required int32 num_input_images = 16;
    total_size += 2 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
        this->_internal_num_input_images());
  }

  if (_internal_has_use_nn()) {
    // required bool use_nn = 6;
    total_size += 1 + 1;
  }

  if (_internal_has_use_scatter_map()) {
    // required bool use_scatter_map = 7;
    total_size += 1 + 1;
  }

  if (_internal_has_done()) {
    // required bool done = 27;
    total_size += 2 + 1;
  }

  if (_internal_has_loaded()) {
    // required bool loaded = 28;
    total_size += 2 + 1;
  }

  if (_internal_has_index_sinogram()) {
    // required int32 index_sinogram = 18;
    total_size += 2 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
        this->_internal_index_sinogram());
  }

  if (_internal_has_index_projection()) {
    // required int32 index_projection = 19;
    total_size += 2 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
        this->_internal_index_projection());
  }

  if (_internal_has_num_detectors()) {
    // required int32 num_detectors = 20;
    total_size += 2 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
        this->_internal_num_detectors());
  }

  if (_internal_has_num_angles()) {
    // required int32 num_angles = 21;
    total_size += 2 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
        this->_internal_num_angles());
  }

  if (_internal_has_num_slices()) {
    // required int32 num_slices = 22;
    total_size += 2 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
        this->_internal_num_slices());
  }

  if (_internal_has_num_results()) {
    // required int32 num_results = 23;
    total_size += 2 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
        this->_internal_num_results());
  }

  if (_internal_has_resolution()) {
    // required int32 resolution = 31;
    total_size += 2 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
        this->_internal_resolution());
  }

  if (_internal_has_file_data_type()) {
    // required .recontaskparameter_pb.ReconTaskParameterPB.FileDataType file_data_type = 17;
    total_size += 2 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::EnumSize(this->_internal_file_data_type());
  }

  return total_size;
}
size_t ReconTaskParameterPB::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:recontaskparameter_pb.ReconTaskParameterPB)
  size_t total_size = 0;

  if (((_has_bits_[0] & 0x0fffefe7) ^ 0x0fffefe7) == 0) {  // All required fields are present.
    // required string task_name = 1;
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_task_name());

    // required string path_sysmat = 2;
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_path_sysmat());

    // required string path_sinogdram = 3;
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_path_sinogdram());

    // required string output_dir = 13;
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_output_dir());

    // required string path_model = 29;
    total_size += 2 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_path_model());

    // required string sinogram_info = 30;
    total_size += 2 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_sinogram_info());

    // required int32 num_iters = 8;
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
        this->_internal_num_iters());

    // required int32 num_dual_iters = 9;
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
        this->_internal_num_dual_iters());

    // required double gamma = 10;
    total_size += 1 + 8;

    // required double lambda = 11;
    total_size += 1 + 8;

    // required .recontaskparameter_pb.ReconTaskParameterPB.IteratorType iterator = 14;
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::EnumSize(this->_internal_iterator());

    // required .recontaskparameter_pb.ReconTaskParameterPB.FileFormat file_format = 15;
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::EnumSize(this->_internal_file_format());

    // required int32 num_input_images = 16;
    total_size += 2 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
        this->_internal_num_input_images());

    // required bool use_nn = 6;
    total_size += 1 + 1;

    // required bool use_scatter_map = 7;
    total_size += 1 + 1;

    // required bool done = 27;
    total_size += 2 + 1;

    // required bool loaded = 28;
    total_size += 2 + 1;

    // required int32 index_sinogram = 18;
    total_size += 2 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
        this->_internal_index_sinogram());

    // required int32 index_projection = 19;
    total_size += 2 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
        this->_internal_index_projection());

    // required int32 num_detectors = 20;
    total_size += 2 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
        this->_internal_num_detectors());

    // required int32 num_angles = 21;
    total_size += 2 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
        this->_internal_num_angles());

    // required int32 num_slices = 22;
    total_size += 2 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
        this->_internal_num_slices());

    // required int32 num_results = 23;
    total_size += 2 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
        this->_internal_num_results());

    // required int32 resolution = 31;
    total_size += 2 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
        this->_internal_resolution());

    // required .recontaskparameter_pb.ReconTaskParameterPB.FileDataType file_data_type = 17;
    total_size += 2 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::EnumSize(this->_internal_file_data_type());

  } else {
    total_size += RequiredFieldsByteSizeFallback();
  }
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated double sinogram_data = 24;
  {
    unsigned int count = static_cast<unsigned int>(this->_internal_sinogram_data_size());
    size_t data_size = 8UL * count;
    total_size += 2 *
                  ::PROTOBUF_NAMESPACE_ID::internal::FromIntSize(this->_internal_sinogram_data_size());
    total_size += data_size;
  }

  // repeated double restored_sinogram_data = 25;
  {
    unsigned int count = static_cast<unsigned int>(this->_internal_restored_sinogram_data_size());
    size_t data_size = 8UL * count;
    total_size += 2 *
                  ::PROTOBUF_NAMESPACE_ID::internal::FromIntSize(this->_internal_restored_sinogram_data_size());
    total_size += data_size;
  }

  // repeated double reconstructed_tomographs_data = 26;
  {
    unsigned int count = static_cast<unsigned int>(this->_internal_reconstructed_tomographs_data_size());
    size_t data_size = 8UL * count;
    total_size += 2 *
                  ::PROTOBUF_NAMESPACE_ID::internal::FromIntSize(this->_internal_reconstructed_tomographs_data_size());
    total_size += data_size;
  }

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x00000018u) {
    // optional string path_scatter_map = 4;
    if (cached_has_bits & 0x00000008u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
          this->_internal_path_scatter_map());
    }

    // optional string path_mu_map = 5;
    if (cached_has_bits & 0x00000010u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
          this->_internal_path_mu_map());
    }

  }
  // optional double coeff_scatter = 12;
  if (cached_has_bits & 0x00001000u) {
    total_size += 1 + 8;
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void ReconTaskParameterPB::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:recontaskparameter_pb.ReconTaskParameterPB)
  GOOGLE_DCHECK_NE(&from, this);
  const ReconTaskParameterPB* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<ReconTaskParameterPB>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:recontaskparameter_pb.ReconTaskParameterPB)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:recontaskparameter_pb.ReconTaskParameterPB)
    MergeFrom(*source);
  }
}

void ReconTaskParameterPB::MergeFrom(const ReconTaskParameterPB& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:recontaskparameter_pb.ReconTaskParameterPB)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  sinogram_data_.MergeFrom(from.sinogram_data_);
  restored_sinogram_data_.MergeFrom(from.restored_sinogram_data_);
  reconstructed_tomographs_data_.MergeFrom(from.reconstructed_tomographs_data_);
  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 0x000000ffu) {
    if (cached_has_bits & 0x00000001u) {
      _internal_set_task_name(from._internal_task_name());
    }
    if (cached_has_bits & 0x00000002u) {
      _internal_set_path_sysmat(from._internal_path_sysmat());
    }
    if (cached_has_bits & 0x00000004u) {
      _internal_set_path_sinogdram(from._internal_path_sinogdram());
    }
    if (cached_has_bits & 0x00000008u) {
      _internal_set_path_scatter_map(from._internal_path_scatter_map());
    }
    if (cached_has_bits & 0x00000010u) {
      _internal_set_path_mu_map(from._internal_path_mu_map());
    }
    if (cached_has_bits & 0x00000020u) {
      _internal_set_output_dir(from._internal_output_dir());
    }
    if (cached_has_bits & 0x00000040u) {
      _internal_set_path_model(from._internal_path_model());
    }
    if (cached_has_bits & 0x00000080u) {
      _internal_set_sinogram_info(from._internal_sinogram_info());
    }
  }
  if (cached_has_bits & 0x0000ff00u) {
    if (cached_has_bits & 0x00000100u) {
      num_iters_ = from.num_iters_;
    }
    if (cached_has_bits & 0x00000200u) {
      num_dual_iters_ = from.num_dual_iters_;
    }
    if (cached_has_bits & 0x00000400u) {
      gamma_ = from.gamma_;
    }
    if (cached_has_bits & 0x00000800u) {
      lambda_ = from.lambda_;
    }
    if (cached_has_bits & 0x00001000u) {
      coeff_scatter_ = from.coeff_scatter_;
    }
    if (cached_has_bits & 0x00002000u) {
      iterator_ = from.iterator_;
    }
    if (cached_has_bits & 0x00004000u) {
      file_format_ = from.file_format_;
    }
    if (cached_has_bits & 0x00008000u) {
      num_input_images_ = from.num_input_images_;
    }
    _has_bits_[0] |= cached_has_bits;
  }
  if (cached_has_bits & 0x00ff0000u) {
    if (cached_has_bits & 0x00010000u) {
      use_nn_ = from.use_nn_;
    }
    if (cached_has_bits & 0x00020000u) {
      use_scatter_map_ = from.use_scatter_map_;
    }
    if (cached_has_bits & 0x00040000u) {
      done_ = from.done_;
    }
    if (cached_has_bits & 0x00080000u) {
      loaded_ = from.loaded_;
    }
    if (cached_has_bits & 0x00100000u) {
      index_sinogram_ = from.index_sinogram_;
    }
    if (cached_has_bits & 0x00200000u) {
      index_projection_ = from.index_projection_;
    }
    if (cached_has_bits & 0x00400000u) {
      num_detectors_ = from.num_detectors_;
    }
    if (cached_has_bits & 0x00800000u) {
      num_angles_ = from.num_angles_;
    }
    _has_bits_[0] |= cached_has_bits;
  }
  if (cached_has_bits & 0x0f000000u) {
    if (cached_has_bits & 0x01000000u) {
      num_slices_ = from.num_slices_;
    }
    if (cached_has_bits & 0x02000000u) {
      num_results_ = from.num_results_;
    }
    if (cached_has_bits & 0x04000000u) {
      resolution_ = from.resolution_;
    }
    if (cached_has_bits & 0x08000000u) {
      file_data_type_ = from.file_data_type_;
    }
    _has_bits_[0] |= cached_has_bits;
  }
}

void ReconTaskParameterPB::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:recontaskparameter_pb.ReconTaskParameterPB)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ReconTaskParameterPB::CopyFrom(const ReconTaskParameterPB& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:recontaskparameter_pb.ReconTaskParameterPB)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ReconTaskParameterPB::IsInitialized() const {
  if (_Internal::MissingRequiredFields(_has_bits_)) return false;
  return true;
}

void ReconTaskParameterPB::InternalSwap(ReconTaskParameterPB* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  sinogram_data_.InternalSwap(&other->sinogram_data_);
  restored_sinogram_data_.InternalSwap(&other->restored_sinogram_data_);
  reconstructed_tomographs_data_.InternalSwap(&other->reconstructed_tomographs_data_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      &task_name_, GetArenaForAllocation(),
      &other->task_name_, other->GetArenaForAllocation()
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      &path_sysmat_, GetArenaForAllocation(),
      &other->path_sysmat_, other->GetArenaForAllocation()
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      &path_sinogdram_, GetArenaForAllocation(),
      &other->path_sinogdram_, other->GetArenaForAllocation()
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      &path_scatter_map_, GetArenaForAllocation(),
      &other->path_scatter_map_, other->GetArenaForAllocation()
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      &path_mu_map_, GetArenaForAllocation(),
      &other->path_mu_map_, other->GetArenaForAllocation()
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      &output_dir_, GetArenaForAllocation(),
      &other->output_dir_, other->GetArenaForAllocation()
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      &path_model_, GetArenaForAllocation(),
      &other->path_model_, other->GetArenaForAllocation()
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      &sinogram_info_, GetArenaForAllocation(),
      &other->sinogram_info_, other->GetArenaForAllocation()
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(ReconTaskParameterPB, resolution_)
      + sizeof(ReconTaskParameterPB::resolution_)
      - PROTOBUF_FIELD_OFFSET(ReconTaskParameterPB, num_iters_)>(
          reinterpret_cast<char*>(&num_iters_),
          reinterpret_cast<char*>(&other->num_iters_));
  swap(file_data_type_, other->file_data_type_);
}

::PROTOBUF_NAMESPACE_ID::Metadata ReconTaskParameterPB::GetMetadata() const {
  return ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(
      &descriptor_table_recontaskparameter_2eproto_getter, &descriptor_table_recontaskparameter_2eproto_once,
      file_level_metadata_recontaskparameter_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace recontaskparameter_pb
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::recontaskparameter_pb::ReconTaskParameterPB* Arena::CreateMaybeMessage< ::recontaskparameter_pb::ReconTaskParameterPB >(Arena* arena) {
  return Arena::CreateMessageInternal< ::recontaskparameter_pb::ReconTaskParameterPB >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
