// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: recontaskparameter.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_recontaskparameter_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_recontaskparameter_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3019000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3019001 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_recontaskparameter_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_recontaskparameter_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_recontaskparameter_2eproto;
namespace recontaskparameter_pb {
class ReconTaskParameterPB;
struct ReconTaskParameterPBDefaultTypeInternal;
extern ReconTaskParameterPBDefaultTypeInternal _ReconTaskParameterPB_default_instance_;
}  // namespace recontaskparameter_pb
PROTOBUF_NAMESPACE_OPEN
template<> ::recontaskparameter_pb::ReconTaskParameterPB* Arena::CreateMaybeMessage<::recontaskparameter_pb::ReconTaskParameterPB>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace recontaskparameter_pb {

enum ReconTaskParameterPB_IteratorType : int {
  ReconTaskParameterPB_IteratorType_MLEM = 0,
  ReconTaskParameterPB_IteratorType_EM_Tikhonov = 1,
  ReconTaskParameterPB_IteratorType_PAPA_2DWavelet = 2,
  ReconTaskParameterPB_IteratorType_PAPA_Cont = 3,
  ReconTaskParameterPB_IteratorType_PAPA_Cont_TV = 4,
  ReconTaskParameterPB_IteratorType_PAPA_Cont_Wavelet = 5,
  ReconTaskParameterPB_IteratorType_PAPA_Dynamic = 6,
  ReconTaskParameterPB_IteratorType_PAPA_TV = 7
};
bool ReconTaskParameterPB_IteratorType_IsValid(int value);
constexpr ReconTaskParameterPB_IteratorType ReconTaskParameterPB_IteratorType_IteratorType_MIN = ReconTaskParameterPB_IteratorType_MLEM;
constexpr ReconTaskParameterPB_IteratorType ReconTaskParameterPB_IteratorType_IteratorType_MAX = ReconTaskParameterPB_IteratorType_PAPA_TV;
constexpr int ReconTaskParameterPB_IteratorType_IteratorType_ARRAYSIZE = ReconTaskParameterPB_IteratorType_IteratorType_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ReconTaskParameterPB_IteratorType_descriptor();
template<typename T>
inline const std::string& ReconTaskParameterPB_IteratorType_Name(T enum_t_value) {
  static_assert(::std::is_same<T, ReconTaskParameterPB_IteratorType>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function ReconTaskParameterPB_IteratorType_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    ReconTaskParameterPB_IteratorType_descriptor(), enum_t_value);
}
inline bool ReconTaskParameterPB_IteratorType_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, ReconTaskParameterPB_IteratorType* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<ReconTaskParameterPB_IteratorType>(
    ReconTaskParameterPB_IteratorType_descriptor(), name, value);
}
enum ReconTaskParameterPB_FileFormat : int {
  ReconTaskParameterPB_FileFormat_RAW_SINOGRAM = 0,
  ReconTaskParameterPB_FileFormat_RAW_PROJECTION = 1,
  ReconTaskParameterPB_FileFormat_DICOM = 2
};
bool ReconTaskParameterPB_FileFormat_IsValid(int value);
constexpr ReconTaskParameterPB_FileFormat ReconTaskParameterPB_FileFormat_FileFormat_MIN = ReconTaskParameterPB_FileFormat_RAW_SINOGRAM;
constexpr ReconTaskParameterPB_FileFormat ReconTaskParameterPB_FileFormat_FileFormat_MAX = ReconTaskParameterPB_FileFormat_DICOM;
constexpr int ReconTaskParameterPB_FileFormat_FileFormat_ARRAYSIZE = ReconTaskParameterPB_FileFormat_FileFormat_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ReconTaskParameterPB_FileFormat_descriptor();
template<typename T>
inline const std::string& ReconTaskParameterPB_FileFormat_Name(T enum_t_value) {
  static_assert(::std::is_same<T, ReconTaskParameterPB_FileFormat>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function ReconTaskParameterPB_FileFormat_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    ReconTaskParameterPB_FileFormat_descriptor(), enum_t_value);
}
inline bool ReconTaskParameterPB_FileFormat_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, ReconTaskParameterPB_FileFormat* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<ReconTaskParameterPB_FileFormat>(
    ReconTaskParameterPB_FileFormat_descriptor(), name, value);
}
enum ReconTaskParameterPB_FileDataType : int {
  ReconTaskParameterPB_FileDataType_FLOAT32 = 1,
  ReconTaskParameterPB_FileDataType_FLOAT64 = 2,
  ReconTaskParameterPB_FileDataType_INT8 = 3,
  ReconTaskParameterPB_FileDataType_UINT8 = 4,
  ReconTaskParameterPB_FileDataType_INT16 = 5,
  ReconTaskParameterPB_FileDataType_UINT16 = 6,
  ReconTaskParameterPB_FileDataType_INT32 = 7,
  ReconTaskParameterPB_FileDataType_UINT32 = 8,
  ReconTaskParameterPB_FileDataType_INT64 = 9,
  ReconTaskParameterPB_FileDataType_UINT64 = 10
};
bool ReconTaskParameterPB_FileDataType_IsValid(int value);
constexpr ReconTaskParameterPB_FileDataType ReconTaskParameterPB_FileDataType_FileDataType_MIN = ReconTaskParameterPB_FileDataType_FLOAT32;
constexpr ReconTaskParameterPB_FileDataType ReconTaskParameterPB_FileDataType_FileDataType_MAX = ReconTaskParameterPB_FileDataType_UINT64;
constexpr int ReconTaskParameterPB_FileDataType_FileDataType_ARRAYSIZE = ReconTaskParameterPB_FileDataType_FileDataType_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ReconTaskParameterPB_FileDataType_descriptor();
template<typename T>
inline const std::string& ReconTaskParameterPB_FileDataType_Name(T enum_t_value) {
  static_assert(::std::is_same<T, ReconTaskParameterPB_FileDataType>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function ReconTaskParameterPB_FileDataType_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    ReconTaskParameterPB_FileDataType_descriptor(), enum_t_value);
}
inline bool ReconTaskParameterPB_FileDataType_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, ReconTaskParameterPB_FileDataType* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<ReconTaskParameterPB_FileDataType>(
    ReconTaskParameterPB_FileDataType_descriptor(), name, value);
}
// ===================================================================

class ReconTaskParameterPB final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:recontaskparameter_pb.ReconTaskParameterPB) */ {
 public:
  inline ReconTaskParameterPB() : ReconTaskParameterPB(nullptr) {}
  ~ReconTaskParameterPB() override;
  explicit constexpr ReconTaskParameterPB(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ReconTaskParameterPB(const ReconTaskParameterPB& from);
  ReconTaskParameterPB(ReconTaskParameterPB&& from) noexcept
    : ReconTaskParameterPB() {
    *this = ::std::move(from);
  }

  inline ReconTaskParameterPB& operator=(const ReconTaskParameterPB& from) {
    CopyFrom(from);
    return *this;
  }
  inline ReconTaskParameterPB& operator=(ReconTaskParameterPB&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ReconTaskParameterPB& default_instance() {
    return *internal_default_instance();
  }
  static inline const ReconTaskParameterPB* internal_default_instance() {
    return reinterpret_cast<const ReconTaskParameterPB*>(
               &_ReconTaskParameterPB_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(ReconTaskParameterPB& a, ReconTaskParameterPB& b) {
    a.Swap(&b);
  }
  inline void Swap(ReconTaskParameterPB* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ReconTaskParameterPB* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ReconTaskParameterPB* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ReconTaskParameterPB>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const ReconTaskParameterPB& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const ReconTaskParameterPB& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ReconTaskParameterPB* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "recontaskparameter_pb.ReconTaskParameterPB";
  }
  protected:
  explicit ReconTaskParameterPB(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  typedef ReconTaskParameterPB_IteratorType IteratorType;
  static constexpr IteratorType MLEM =
    ReconTaskParameterPB_IteratorType_MLEM;
  static constexpr IteratorType EM_Tikhonov =
    ReconTaskParameterPB_IteratorType_EM_Tikhonov;
  static constexpr IteratorType PAPA_2DWavelet =
    ReconTaskParameterPB_IteratorType_PAPA_2DWavelet;
  static constexpr IteratorType PAPA_Cont =
    ReconTaskParameterPB_IteratorType_PAPA_Cont;
  static constexpr IteratorType PAPA_Cont_TV =
    ReconTaskParameterPB_IteratorType_PAPA_Cont_TV;
  static constexpr IteratorType PAPA_Cont_Wavelet =
    ReconTaskParameterPB_IteratorType_PAPA_Cont_Wavelet;
  static constexpr IteratorType PAPA_Dynamic =
    ReconTaskParameterPB_IteratorType_PAPA_Dynamic;
  static constexpr IteratorType PAPA_TV =
    ReconTaskParameterPB_IteratorType_PAPA_TV;
  static inline bool IteratorType_IsValid(int value) {
    return ReconTaskParameterPB_IteratorType_IsValid(value);
  }
  static constexpr IteratorType IteratorType_MIN =
    ReconTaskParameterPB_IteratorType_IteratorType_MIN;
  static constexpr IteratorType IteratorType_MAX =
    ReconTaskParameterPB_IteratorType_IteratorType_MAX;
  static constexpr int IteratorType_ARRAYSIZE =
    ReconTaskParameterPB_IteratorType_IteratorType_ARRAYSIZE;
  static inline const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor*
  IteratorType_descriptor() {
    return ReconTaskParameterPB_IteratorType_descriptor();
  }
  template<typename T>
  static inline const std::string& IteratorType_Name(T enum_t_value) {
    static_assert(::std::is_same<T, IteratorType>::value ||
      ::std::is_integral<T>::value,
      "Incorrect type passed to function IteratorType_Name.");
    return ReconTaskParameterPB_IteratorType_Name(enum_t_value);
  }
  static inline bool IteratorType_Parse(::PROTOBUF_NAMESPACE_ID::ConstStringParam name,
      IteratorType* value) {
    return ReconTaskParameterPB_IteratorType_Parse(name, value);
  }

  typedef ReconTaskParameterPB_FileFormat FileFormat;
  static constexpr FileFormat RAW_SINOGRAM =
    ReconTaskParameterPB_FileFormat_RAW_SINOGRAM;
  static constexpr FileFormat RAW_PROJECTION =
    ReconTaskParameterPB_FileFormat_RAW_PROJECTION;
  static constexpr FileFormat DICOM =
    ReconTaskParameterPB_FileFormat_DICOM;
  static inline bool FileFormat_IsValid(int value) {
    return ReconTaskParameterPB_FileFormat_IsValid(value);
  }
  static constexpr FileFormat FileFormat_MIN =
    ReconTaskParameterPB_FileFormat_FileFormat_MIN;
  static constexpr FileFormat FileFormat_MAX =
    ReconTaskParameterPB_FileFormat_FileFormat_MAX;
  static constexpr int FileFormat_ARRAYSIZE =
    ReconTaskParameterPB_FileFormat_FileFormat_ARRAYSIZE;
  static inline const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor*
  FileFormat_descriptor() {
    return ReconTaskParameterPB_FileFormat_descriptor();
  }
  template<typename T>
  static inline const std::string& FileFormat_Name(T enum_t_value) {
    static_assert(::std::is_same<T, FileFormat>::value ||
      ::std::is_integral<T>::value,
      "Incorrect type passed to function FileFormat_Name.");
    return ReconTaskParameterPB_FileFormat_Name(enum_t_value);
  }
  static inline bool FileFormat_Parse(::PROTOBUF_NAMESPACE_ID::ConstStringParam name,
      FileFormat* value) {
    return ReconTaskParameterPB_FileFormat_Parse(name, value);
  }

  typedef ReconTaskParameterPB_FileDataType FileDataType;
  static constexpr FileDataType FLOAT32 =
    ReconTaskParameterPB_FileDataType_FLOAT32;
  static constexpr FileDataType FLOAT64 =
    ReconTaskParameterPB_FileDataType_FLOAT64;
  static constexpr FileDataType INT8 =
    ReconTaskParameterPB_FileDataType_INT8;
  static constexpr FileDataType UINT8 =
    ReconTaskParameterPB_FileDataType_UINT8;
  static constexpr FileDataType INT16 =
    ReconTaskParameterPB_FileDataType_INT16;
  static constexpr FileDataType UINT16 =
    ReconTaskParameterPB_FileDataType_UINT16;
  static constexpr FileDataType INT32 =
    ReconTaskParameterPB_FileDataType_INT32;
  static constexpr FileDataType UINT32 =
    ReconTaskParameterPB_FileDataType_UINT32;
  static constexpr FileDataType INT64 =
    ReconTaskParameterPB_FileDataType_INT64;
  static constexpr FileDataType UINT64 =
    ReconTaskParameterPB_FileDataType_UINT64;
  static inline bool FileDataType_IsValid(int value) {
    return ReconTaskParameterPB_FileDataType_IsValid(value);
  }
  static constexpr FileDataType FileDataType_MIN =
    ReconTaskParameterPB_FileDataType_FileDataType_MIN;
  static constexpr FileDataType FileDataType_MAX =
    ReconTaskParameterPB_FileDataType_FileDataType_MAX;
  static constexpr int FileDataType_ARRAYSIZE =
    ReconTaskParameterPB_FileDataType_FileDataType_ARRAYSIZE;
  static inline const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor*
  FileDataType_descriptor() {
    return ReconTaskParameterPB_FileDataType_descriptor();
  }
  template<typename T>
  static inline const std::string& FileDataType_Name(T enum_t_value) {
    static_assert(::std::is_same<T, FileDataType>::value ||
      ::std::is_integral<T>::value,
      "Incorrect type passed to function FileDataType_Name.");
    return ReconTaskParameterPB_FileDataType_Name(enum_t_value);
  }
  static inline bool FileDataType_Parse(::PROTOBUF_NAMESPACE_ID::ConstStringParam name,
      FileDataType* value) {
    return ReconTaskParameterPB_FileDataType_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  enum : int {
    kSinogramDataFieldNumber = 24,
    kRestoredSinogramDataFieldNumber = 25,
    kReconstructedTomographsDataFieldNumber = 26,
    kTaskNameFieldNumber = 1,
    kPathSysmatFieldNumber = 2,
    kPathSinogdramFieldNumber = 3,
    kPathScatterMapFieldNumber = 4,
    kPathMuMapFieldNumber = 5,
    kOutputDirFieldNumber = 13,
    kPathModelFieldNumber = 29,
    kSinogramInfoFieldNumber = 30,
    kNumItersFieldNumber = 8,
    kNumDualItersFieldNumber = 9,
    kGammaFieldNumber = 10,
    kLambdaFieldNumber = 11,
    kCoeffScatterFieldNumber = 12,
    kIteratorFieldNumber = 14,
    kFileFormatFieldNumber = 15,
    kNumInputImagesFieldNumber = 16,
    kUseNnFieldNumber = 6,
    kUseScatterMapFieldNumber = 7,
    kDoneFieldNumber = 27,
    kLoadedFieldNumber = 28,
    kIndexSinogramFieldNumber = 18,
    kIndexProjectionFieldNumber = 19,
    kNumDetectorsFieldNumber = 20,
    kNumAnglesFieldNumber = 21,
    kNumSlicesFieldNumber = 22,
    kNumResultsFieldNumber = 23,
    kResolutionFieldNumber = 31,
    kFileDataTypeFieldNumber = 17,
  };
  // repeated double sinogram_data = 24;
  int sinogram_data_size() const;
  private:
  int _internal_sinogram_data_size() const;
  public:
  void clear_sinogram_data();
  private:
  double _internal_sinogram_data(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >&
      _internal_sinogram_data() const;
  void _internal_add_sinogram_data(double value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >*
      _internal_mutable_sinogram_data();
  public:
  double sinogram_data(int index) const;
  void set_sinogram_data(int index, double value);
  void add_sinogram_data(double value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >&
      sinogram_data() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >*
      mutable_sinogram_data();

  // repeated double restored_sinogram_data = 25;
  int restored_sinogram_data_size() const;
  private:
  int _internal_restored_sinogram_data_size() const;
  public:
  void clear_restored_sinogram_data();
  private:
  double _internal_restored_sinogram_data(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >&
      _internal_restored_sinogram_data() const;
  void _internal_add_restored_sinogram_data(double value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >*
      _internal_mutable_restored_sinogram_data();
  public:
  double restored_sinogram_data(int index) const;
  void set_restored_sinogram_data(int index, double value);
  void add_restored_sinogram_data(double value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >&
      restored_sinogram_data() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >*
      mutable_restored_sinogram_data();

  // repeated double reconstructed_tomographs_data = 26;
  int reconstructed_tomographs_data_size() const;
  private:
  int _internal_reconstructed_tomographs_data_size() const;
  public:
  void clear_reconstructed_tomographs_data();
  private:
  double _internal_reconstructed_tomographs_data(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >&
      _internal_reconstructed_tomographs_data() const;
  void _internal_add_reconstructed_tomographs_data(double value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >*
      _internal_mutable_reconstructed_tomographs_data();
  public:
  double reconstructed_tomographs_data(int index) const;
  void set_reconstructed_tomographs_data(int index, double value);
  void add_reconstructed_tomographs_data(double value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >&
      reconstructed_tomographs_data() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >*
      mutable_reconstructed_tomographs_data();

  // required string task_name = 1;
  bool has_task_name() const;
  private:
  bool _internal_has_task_name() const;
  public:
  void clear_task_name();
  const std::string& task_name() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_task_name(ArgT0&& arg0, ArgT... args);
  std::string* mutable_task_name();
  PROTOBUF_NODISCARD std::string* release_task_name();
  void set_allocated_task_name(std::string* task_name);
  private:
  const std::string& _internal_task_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_task_name(const std::string& value);
  std::string* _internal_mutable_task_name();
  public:

  // required string path_sysmat = 2;
  bool has_path_sysmat() const;
  private:
  bool _internal_has_path_sysmat() const;
  public:
  void clear_path_sysmat();
  const std::string& path_sysmat() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_path_sysmat(ArgT0&& arg0, ArgT... args);
  std::string* mutable_path_sysmat();
  PROTOBUF_NODISCARD std::string* release_path_sysmat();
  void set_allocated_path_sysmat(std::string* path_sysmat);
  private:
  const std::string& _internal_path_sysmat() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_path_sysmat(const std::string& value);
  std::string* _internal_mutable_path_sysmat();
  public:

  // required string path_sinogdram = 3;
  bool has_path_sinogdram() const;
  private:
  bool _internal_has_path_sinogdram() const;
  public:
  void clear_path_sinogdram();
  const std::string& path_sinogdram() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_path_sinogdram(ArgT0&& arg0, ArgT... args);
  std::string* mutable_path_sinogdram();
  PROTOBUF_NODISCARD std::string* release_path_sinogdram();
  void set_allocated_path_sinogdram(std::string* path_sinogdram);
  private:
  const std::string& _internal_path_sinogdram() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_path_sinogdram(const std::string& value);
  std::string* _internal_mutable_path_sinogdram();
  public:

  // optional string path_scatter_map = 4;
  bool has_path_scatter_map() const;
  private:
  bool _internal_has_path_scatter_map() const;
  public:
  void clear_path_scatter_map();
  const std::string& path_scatter_map() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_path_scatter_map(ArgT0&& arg0, ArgT... args);
  std::string* mutable_path_scatter_map();
  PROTOBUF_NODISCARD std::string* release_path_scatter_map();
  void set_allocated_path_scatter_map(std::string* path_scatter_map);
  private:
  const std::string& _internal_path_scatter_map() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_path_scatter_map(const std::string& value);
  std::string* _internal_mutable_path_scatter_map();
  public:

  // optional string path_mu_map = 5;
  bool has_path_mu_map() const;
  private:
  bool _internal_has_path_mu_map() const;
  public:
  void clear_path_mu_map();
  const std::string& path_mu_map() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_path_mu_map(ArgT0&& arg0, ArgT... args);
  std::string* mutable_path_mu_map();
  PROTOBUF_NODISCARD std::string* release_path_mu_map();
  void set_allocated_path_mu_map(std::string* path_mu_map);
  private:
  const std::string& _internal_path_mu_map() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_path_mu_map(const std::string& value);
  std::string* _internal_mutable_path_mu_map();
  public:

  // required string output_dir = 13;
  bool has_output_dir() const;
  private:
  bool _internal_has_output_dir() const;
  public:
  void clear_output_dir();
  const std::string& output_dir() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_output_dir(ArgT0&& arg0, ArgT... args);
  std::string* mutable_output_dir();
  PROTOBUF_NODISCARD std::string* release_output_dir();
  void set_allocated_output_dir(std::string* output_dir);
  private:
  const std::string& _internal_output_dir() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_output_dir(const std::string& value);
  std::string* _internal_mutable_output_dir();
  public:

  // required string path_model = 29;
  bool has_path_model() const;
  private:
  bool _internal_has_path_model() const;
  public:
  void clear_path_model();
  const std::string& path_model() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_path_model(ArgT0&& arg0, ArgT... args);
  std::string* mutable_path_model();
  PROTOBUF_NODISCARD std::string* release_path_model();
  void set_allocated_path_model(std::string* path_model);
  private:
  const std::string& _internal_path_model() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_path_model(const std::string& value);
  std::string* _internal_mutable_path_model();
  public:

  // required string sinogram_info = 30;
  bool has_sinogram_info() const;
  private:
  bool _internal_has_sinogram_info() const;
  public:
  void clear_sinogram_info();
  const std::string& sinogram_info() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_sinogram_info(ArgT0&& arg0, ArgT... args);
  std::string* mutable_sinogram_info();
  PROTOBUF_NODISCARD std::string* release_sinogram_info();
  void set_allocated_sinogram_info(std::string* sinogram_info);
  private:
  const std::string& _internal_sinogram_info() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_sinogram_info(const std::string& value);
  std::string* _internal_mutable_sinogram_info();
  public:

  // required int32 num_iters = 8;
  bool has_num_iters() const;
  private:
  bool _internal_has_num_iters() const;
  public:
  void clear_num_iters();
  int32_t num_iters() const;
  void set_num_iters(int32_t value);
  private:
  int32_t _internal_num_iters() const;
  void _internal_set_num_iters(int32_t value);
  public:

  // required int32 num_dual_iters = 9;
  bool has_num_dual_iters() const;
  private:
  bool _internal_has_num_dual_iters() const;
  public:
  void clear_num_dual_iters();
  int32_t num_dual_iters() const;
  void set_num_dual_iters(int32_t value);
  private:
  int32_t _internal_num_dual_iters() const;
  void _internal_set_num_dual_iters(int32_t value);
  public:

  // required double gamma = 10;
  bool has_gamma() const;
  private:
  bool _internal_has_gamma() const;
  public:
  void clear_gamma();
  double gamma() const;
  void set_gamma(double value);
  private:
  double _internal_gamma() const;
  void _internal_set_gamma(double value);
  public:

  // required double lambda = 11;
  bool has_lambda() const;
  private:
  bool _internal_has_lambda() const;
  public:
  void clear_lambda();
  double lambda() const;
  void set_lambda(double value);
  private:
  double _internal_lambda() const;
  void _internal_set_lambda(double value);
  public:

  // optional double coeff_scatter = 12;
  bool has_coeff_scatter() const;
  private:
  bool _internal_has_coeff_scatter() const;
  public:
  void clear_coeff_scatter();
  double coeff_scatter() const;
  void set_coeff_scatter(double value);
  private:
  double _internal_coeff_scatter() const;
  void _internal_set_coeff_scatter(double value);
  public:

  // required .recontaskparameter_pb.ReconTaskParameterPB.IteratorType iterator = 14;
  bool has_iterator() const;
  private:
  bool _internal_has_iterator() const;
  public:
  void clear_iterator();
  ::recontaskparameter_pb::ReconTaskParameterPB_IteratorType iterator() const;
  void set_iterator(::recontaskparameter_pb::ReconTaskParameterPB_IteratorType value);
  private:
  ::recontaskparameter_pb::ReconTaskParameterPB_IteratorType _internal_iterator() const;
  void _internal_set_iterator(::recontaskparameter_pb::ReconTaskParameterPB_IteratorType value);
  public:

  // required .recontaskparameter_pb.ReconTaskParameterPB.FileFormat file_format = 15;
  bool has_file_format() const;
  private:
  bool _internal_has_file_format() const;
  public:
  void clear_file_format();
  ::recontaskparameter_pb::ReconTaskParameterPB_FileFormat file_format() const;
  void set_file_format(::recontaskparameter_pb::ReconTaskParameterPB_FileFormat value);
  private:
  ::recontaskparameter_pb::ReconTaskParameterPB_FileFormat _internal_file_format() const;
  void _internal_set_file_format(::recontaskparameter_pb::ReconTaskParameterPB_FileFormat value);
  public:

  // required int32 num_input_images = 16;
  bool has_num_input_images() const;
  private:
  bool _internal_has_num_input_images() const;
  public:
  void clear_num_input_images();
  int32_t num_input_images() const;
  void set_num_input_images(int32_t value);
  private:
  int32_t _internal_num_input_images() const;
  void _internal_set_num_input_images(int32_t value);
  public:

  // required bool use_nn = 6;
  bool has_use_nn() const;
  private:
  bool _internal_has_use_nn() const;
  public:
  void clear_use_nn();
  bool use_nn() const;
  void set_use_nn(bool value);
  private:
  bool _internal_use_nn() const;
  void _internal_set_use_nn(bool value);
  public:

  // required bool use_scatter_map = 7;
  bool has_use_scatter_map() const;
  private:
  bool _internal_has_use_scatter_map() const;
  public:
  void clear_use_scatter_map();
  bool use_scatter_map() const;
  void set_use_scatter_map(bool value);
  private:
  bool _internal_use_scatter_map() const;
  void _internal_set_use_scatter_map(bool value);
  public:

  // required bool done = 27;
  bool has_done() const;
  private:
  bool _internal_has_done() const;
  public:
  void clear_done();
  bool done() const;
  void set_done(bool value);
  private:
  bool _internal_done() const;
  void _internal_set_done(bool value);
  public:

  // required bool loaded = 28;
  bool has_loaded() const;
  private:
  bool _internal_has_loaded() const;
  public:
  void clear_loaded();
  bool loaded() const;
  void set_loaded(bool value);
  private:
  bool _internal_loaded() const;
  void _internal_set_loaded(bool value);
  public:

  // required int32 index_sinogram = 18;
  bool has_index_sinogram() const;
  private:
  bool _internal_has_index_sinogram() const;
  public:
  void clear_index_sinogram();
  int32_t index_sinogram() const;
  void set_index_sinogram(int32_t value);
  private:
  int32_t _internal_index_sinogram() const;
  void _internal_set_index_sinogram(int32_t value);
  public:

  // required int32 index_projection = 19;
  bool has_index_projection() const;
  private:
  bool _internal_has_index_projection() const;
  public:
  void clear_index_projection();
  int32_t index_projection() const;
  void set_index_projection(int32_t value);
  private:
  int32_t _internal_index_projection() const;
  void _internal_set_index_projection(int32_t value);
  public:

  // required int32 num_detectors = 20;
  bool has_num_detectors() const;
  private:
  bool _internal_has_num_detectors() const;
  public:
  void clear_num_detectors();
  int32_t num_detectors() const;
  void set_num_detectors(int32_t value);
  private:
  int32_t _internal_num_detectors() const;
  void _internal_set_num_detectors(int32_t value);
  public:

  // required int32 num_angles = 21;
  bool has_num_angles() const;
  private:
  bool _internal_has_num_angles() const;
  public:
  void clear_num_angles();
  int32_t num_angles() const;
  void set_num_angles(int32_t value);
  private:
  int32_t _internal_num_angles() const;
  void _internal_set_num_angles(int32_t value);
  public:

  // required int32 num_slices = 22;
  bool has_num_slices() const;
  private:
  bool _internal_has_num_slices() const;
  public:
  void clear_num_slices();
  int32_t num_slices() const;
  void set_num_slices(int32_t value);
  private:
  int32_t _internal_num_slices() const;
  void _internal_set_num_slices(int32_t value);
  public:

  // required int32 num_results = 23;
  bool has_num_results() const;
  private:
  bool _internal_has_num_results() const;
  public:
  void clear_num_results();
  int32_t num_results() const;
  void set_num_results(int32_t value);
  private:
  int32_t _internal_num_results() const;
  void _internal_set_num_results(int32_t value);
  public:

  // required int32 resolution = 31;
  bool has_resolution() const;
  private:
  bool _internal_has_resolution() const;
  public:
  void clear_resolution();
  int32_t resolution() const;
  void set_resolution(int32_t value);
  private:
  int32_t _internal_resolution() const;
  void _internal_set_resolution(int32_t value);
  public:

  // required .recontaskparameter_pb.ReconTaskParameterPB.FileDataType file_data_type = 17;
  bool has_file_data_type() const;
  private:
  bool _internal_has_file_data_type() const;
  public:
  void clear_file_data_type();
  ::recontaskparameter_pb::ReconTaskParameterPB_FileDataType file_data_type() const;
  void set_file_data_type(::recontaskparameter_pb::ReconTaskParameterPB_FileDataType value);
  private:
  ::recontaskparameter_pb::ReconTaskParameterPB_FileDataType _internal_file_data_type() const;
  void _internal_set_file_data_type(::recontaskparameter_pb::ReconTaskParameterPB_FileDataType value);
  public:

  // @@protoc_insertion_point(class_scope:recontaskparameter_pb.ReconTaskParameterPB)
 private:
  class _Internal;

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< double > sinogram_data_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< double > restored_sinogram_data_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< double > reconstructed_tomographs_data_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr task_name_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr path_sysmat_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr path_sinogdram_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr path_scatter_map_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr path_mu_map_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr output_dir_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr path_model_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr sinogram_info_;
  int32_t num_iters_;
  int32_t num_dual_iters_;
  double gamma_;
  double lambda_;
  double coeff_scatter_;
  int iterator_;
  int file_format_;
  int32_t num_input_images_;
  bool use_nn_;
  bool use_scatter_map_;
  bool done_;
  bool loaded_;
  int32_t index_sinogram_;
  int32_t index_projection_;
  int32_t num_detectors_;
  int32_t num_angles_;
  int32_t num_slices_;
  int32_t num_results_;
  int32_t resolution_;
  int file_data_type_;
  friend struct ::TableStruct_recontaskparameter_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// ReconTaskParameterPB

// required string task_name = 1;
inline bool ReconTaskParameterPB::_internal_has_task_name() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool ReconTaskParameterPB::has_task_name() const {
  return _internal_has_task_name();
}
inline void ReconTaskParameterPB::clear_task_name() {
  task_name_.ClearToEmpty();
  _has_bits_[0] &= ~0x00000001u;
}
inline const std::string& ReconTaskParameterPB::task_name() const {
  // @@protoc_insertion_point(field_get:recontaskparameter_pb.ReconTaskParameterPB.task_name)
  return _internal_task_name();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void ReconTaskParameterPB::set_task_name(ArgT0&& arg0, ArgT... args) {
 _has_bits_[0] |= 0x00000001u;
 task_name_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:recontaskparameter_pb.ReconTaskParameterPB.task_name)
}
inline std::string* ReconTaskParameterPB::mutable_task_name() {
  std::string* _s = _internal_mutable_task_name();
  // @@protoc_insertion_point(field_mutable:recontaskparameter_pb.ReconTaskParameterPB.task_name)
  return _s;
}
inline const std::string& ReconTaskParameterPB::_internal_task_name() const {
  return task_name_.Get();
}
inline void ReconTaskParameterPB::_internal_set_task_name(const std::string& value) {
  _has_bits_[0] |= 0x00000001u;
  task_name_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* ReconTaskParameterPB::_internal_mutable_task_name() {
  _has_bits_[0] |= 0x00000001u;
  return task_name_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* ReconTaskParameterPB::release_task_name() {
  // @@protoc_insertion_point(field_release:recontaskparameter_pb.ReconTaskParameterPB.task_name)
  if (!_internal_has_task_name()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000001u;
  auto* p = task_name_.ReleaseNonDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (task_name_.IsDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited())) {
    task_name_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return p;
}
inline void ReconTaskParameterPB::set_allocated_task_name(std::string* task_name) {
  if (task_name != nullptr) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  task_name_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), task_name,
      GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (task_name_.IsDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited())) {
    task_name_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:recontaskparameter_pb.ReconTaskParameterPB.task_name)
}

// required string path_sysmat = 2;
inline bool ReconTaskParameterPB::_internal_has_path_sysmat() const {
  bool value = (_has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool ReconTaskParameterPB::has_path_sysmat() const {
  return _internal_has_path_sysmat();
}
inline void ReconTaskParameterPB::clear_path_sysmat() {
  path_sysmat_.ClearToEmpty();
  _has_bits_[0] &= ~0x00000002u;
}
inline const std::string& ReconTaskParameterPB::path_sysmat() const {
  // @@protoc_insertion_point(field_get:recontaskparameter_pb.ReconTaskParameterPB.path_sysmat)
  return _internal_path_sysmat();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void ReconTaskParameterPB::set_path_sysmat(ArgT0&& arg0, ArgT... args) {
 _has_bits_[0] |= 0x00000002u;
 path_sysmat_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:recontaskparameter_pb.ReconTaskParameterPB.path_sysmat)
}
inline std::string* ReconTaskParameterPB::mutable_path_sysmat() {
  std::string* _s = _internal_mutable_path_sysmat();
  // @@protoc_insertion_point(field_mutable:recontaskparameter_pb.ReconTaskParameterPB.path_sysmat)
  return _s;
}
inline const std::string& ReconTaskParameterPB::_internal_path_sysmat() const {
  return path_sysmat_.Get();
}
inline void ReconTaskParameterPB::_internal_set_path_sysmat(const std::string& value) {
  _has_bits_[0] |= 0x00000002u;
  path_sysmat_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* ReconTaskParameterPB::_internal_mutable_path_sysmat() {
  _has_bits_[0] |= 0x00000002u;
  return path_sysmat_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* ReconTaskParameterPB::release_path_sysmat() {
  // @@protoc_insertion_point(field_release:recontaskparameter_pb.ReconTaskParameterPB.path_sysmat)
  if (!_internal_has_path_sysmat()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000002u;
  auto* p = path_sysmat_.ReleaseNonDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (path_sysmat_.IsDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited())) {
    path_sysmat_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return p;
}
inline void ReconTaskParameterPB::set_allocated_path_sysmat(std::string* path_sysmat) {
  if (path_sysmat != nullptr) {
    _has_bits_[0] |= 0x00000002u;
  } else {
    _has_bits_[0] &= ~0x00000002u;
  }
  path_sysmat_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), path_sysmat,
      GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (path_sysmat_.IsDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited())) {
    path_sysmat_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:recontaskparameter_pb.ReconTaskParameterPB.path_sysmat)
}

// required string path_sinogdram = 3;
inline bool ReconTaskParameterPB::_internal_has_path_sinogdram() const {
  bool value = (_has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline bool ReconTaskParameterPB::has_path_sinogdram() const {
  return _internal_has_path_sinogdram();
}
inline void ReconTaskParameterPB::clear_path_sinogdram() {
  path_sinogdram_.ClearToEmpty();
  _has_bits_[0] &= ~0x00000004u;
}
inline const std::string& ReconTaskParameterPB::path_sinogdram() const {
  // @@protoc_insertion_point(field_get:recontaskparameter_pb.ReconTaskParameterPB.path_sinogdram)
  return _internal_path_sinogdram();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void ReconTaskParameterPB::set_path_sinogdram(ArgT0&& arg0, ArgT... args) {
 _has_bits_[0] |= 0x00000004u;
 path_sinogdram_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:recontaskparameter_pb.ReconTaskParameterPB.path_sinogdram)
}
inline std::string* ReconTaskParameterPB::mutable_path_sinogdram() {
  std::string* _s = _internal_mutable_path_sinogdram();
  // @@protoc_insertion_point(field_mutable:recontaskparameter_pb.ReconTaskParameterPB.path_sinogdram)
  return _s;
}
inline const std::string& ReconTaskParameterPB::_internal_path_sinogdram() const {
  return path_sinogdram_.Get();
}
inline void ReconTaskParameterPB::_internal_set_path_sinogdram(const std::string& value) {
  _has_bits_[0] |= 0x00000004u;
  path_sinogdram_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* ReconTaskParameterPB::_internal_mutable_path_sinogdram() {
  _has_bits_[0] |= 0x00000004u;
  return path_sinogdram_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* ReconTaskParameterPB::release_path_sinogdram() {
  // @@protoc_insertion_point(field_release:recontaskparameter_pb.ReconTaskParameterPB.path_sinogdram)
  if (!_internal_has_path_sinogdram()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000004u;
  auto* p = path_sinogdram_.ReleaseNonDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (path_sinogdram_.IsDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited())) {
    path_sinogdram_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return p;
}
inline void ReconTaskParameterPB::set_allocated_path_sinogdram(std::string* path_sinogdram) {
  if (path_sinogdram != nullptr) {
    _has_bits_[0] |= 0x00000004u;
  } else {
    _has_bits_[0] &= ~0x00000004u;
  }
  path_sinogdram_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), path_sinogdram,
      GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (path_sinogdram_.IsDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited())) {
    path_sinogdram_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:recontaskparameter_pb.ReconTaskParameterPB.path_sinogdram)
}

// optional string path_scatter_map = 4;
inline bool ReconTaskParameterPB::_internal_has_path_scatter_map() const {
  bool value = (_has_bits_[0] & 0x00000008u) != 0;
  return value;
}
inline bool ReconTaskParameterPB::has_path_scatter_map() const {
  return _internal_has_path_scatter_map();
}
inline void ReconTaskParameterPB::clear_path_scatter_map() {
  path_scatter_map_.ClearToEmpty();
  _has_bits_[0] &= ~0x00000008u;
}
inline const std::string& ReconTaskParameterPB::path_scatter_map() const {
  // @@protoc_insertion_point(field_get:recontaskparameter_pb.ReconTaskParameterPB.path_scatter_map)
  return _internal_path_scatter_map();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void ReconTaskParameterPB::set_path_scatter_map(ArgT0&& arg0, ArgT... args) {
 _has_bits_[0] |= 0x00000008u;
 path_scatter_map_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:recontaskparameter_pb.ReconTaskParameterPB.path_scatter_map)
}
inline std::string* ReconTaskParameterPB::mutable_path_scatter_map() {
  std::string* _s = _internal_mutable_path_scatter_map();
  // @@protoc_insertion_point(field_mutable:recontaskparameter_pb.ReconTaskParameterPB.path_scatter_map)
  return _s;
}
inline const std::string& ReconTaskParameterPB::_internal_path_scatter_map() const {
  return path_scatter_map_.Get();
}
inline void ReconTaskParameterPB::_internal_set_path_scatter_map(const std::string& value) {
  _has_bits_[0] |= 0x00000008u;
  path_scatter_map_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* ReconTaskParameterPB::_internal_mutable_path_scatter_map() {
  _has_bits_[0] |= 0x00000008u;
  return path_scatter_map_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* ReconTaskParameterPB::release_path_scatter_map() {
  // @@protoc_insertion_point(field_release:recontaskparameter_pb.ReconTaskParameterPB.path_scatter_map)
  if (!_internal_has_path_scatter_map()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000008u;
  auto* p = path_scatter_map_.ReleaseNonDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (path_scatter_map_.IsDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited())) {
    path_scatter_map_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return p;
}
inline void ReconTaskParameterPB::set_allocated_path_scatter_map(std::string* path_scatter_map) {
  if (path_scatter_map != nullptr) {
    _has_bits_[0] |= 0x00000008u;
  } else {
    _has_bits_[0] &= ~0x00000008u;
  }
  path_scatter_map_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), path_scatter_map,
      GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (path_scatter_map_.IsDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited())) {
    path_scatter_map_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:recontaskparameter_pb.ReconTaskParameterPB.path_scatter_map)
}

// optional string path_mu_map = 5;
inline bool ReconTaskParameterPB::_internal_has_path_mu_map() const {
  bool value = (_has_bits_[0] & 0x00000010u) != 0;
  return value;
}
inline bool ReconTaskParameterPB::has_path_mu_map() const {
  return _internal_has_path_mu_map();
}
inline void ReconTaskParameterPB::clear_path_mu_map() {
  path_mu_map_.ClearToEmpty();
  _has_bits_[0] &= ~0x00000010u;
}
inline const std::string& ReconTaskParameterPB::path_mu_map() const {
  // @@protoc_insertion_point(field_get:recontaskparameter_pb.ReconTaskParameterPB.path_mu_map)
  return _internal_path_mu_map();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void ReconTaskParameterPB::set_path_mu_map(ArgT0&& arg0, ArgT... args) {
 _has_bits_[0] |= 0x00000010u;
 path_mu_map_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:recontaskparameter_pb.ReconTaskParameterPB.path_mu_map)
}
inline std::string* ReconTaskParameterPB::mutable_path_mu_map() {
  std::string* _s = _internal_mutable_path_mu_map();
  // @@protoc_insertion_point(field_mutable:recontaskparameter_pb.ReconTaskParameterPB.path_mu_map)
  return _s;
}
inline const std::string& ReconTaskParameterPB::_internal_path_mu_map() const {
  return path_mu_map_.Get();
}
inline void ReconTaskParameterPB::_internal_set_path_mu_map(const std::string& value) {
  _has_bits_[0] |= 0x00000010u;
  path_mu_map_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* ReconTaskParameterPB::_internal_mutable_path_mu_map() {
  _has_bits_[0] |= 0x00000010u;
  return path_mu_map_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* ReconTaskParameterPB::release_path_mu_map() {
  // @@protoc_insertion_point(field_release:recontaskparameter_pb.ReconTaskParameterPB.path_mu_map)
  if (!_internal_has_path_mu_map()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000010u;
  auto* p = path_mu_map_.ReleaseNonDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (path_mu_map_.IsDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited())) {
    path_mu_map_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return p;
}
inline void ReconTaskParameterPB::set_allocated_path_mu_map(std::string* path_mu_map) {
  if (path_mu_map != nullptr) {
    _has_bits_[0] |= 0x00000010u;
  } else {
    _has_bits_[0] &= ~0x00000010u;
  }
  path_mu_map_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), path_mu_map,
      GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (path_mu_map_.IsDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited())) {
    path_mu_map_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:recontaskparameter_pb.ReconTaskParameterPB.path_mu_map)
}

// required bool use_nn = 6;
inline bool ReconTaskParameterPB::_internal_has_use_nn() const {
  bool value = (_has_bits_[0] & 0x00010000u) != 0;
  return value;
}
inline bool ReconTaskParameterPB::has_use_nn() const {
  return _internal_has_use_nn();
}
inline void ReconTaskParameterPB::clear_use_nn() {
  use_nn_ = false;
  _has_bits_[0] &= ~0x00010000u;
}
inline bool ReconTaskParameterPB::_internal_use_nn() const {
  return use_nn_;
}
inline bool ReconTaskParameterPB::use_nn() const {
  // @@protoc_insertion_point(field_get:recontaskparameter_pb.ReconTaskParameterPB.use_nn)
  return _internal_use_nn();
}
inline void ReconTaskParameterPB::_internal_set_use_nn(bool value) {
  _has_bits_[0] |= 0x00010000u;
  use_nn_ = value;
}
inline void ReconTaskParameterPB::set_use_nn(bool value) {
  _internal_set_use_nn(value);
  // @@protoc_insertion_point(field_set:recontaskparameter_pb.ReconTaskParameterPB.use_nn)
}

// required bool use_scatter_map = 7;
inline bool ReconTaskParameterPB::_internal_has_use_scatter_map() const {
  bool value = (_has_bits_[0] & 0x00020000u) != 0;
  return value;
}
inline bool ReconTaskParameterPB::has_use_scatter_map() const {
  return _internal_has_use_scatter_map();
}
inline void ReconTaskParameterPB::clear_use_scatter_map() {
  use_scatter_map_ = false;
  _has_bits_[0] &= ~0x00020000u;
}
inline bool ReconTaskParameterPB::_internal_use_scatter_map() const {
  return use_scatter_map_;
}
inline bool ReconTaskParameterPB::use_scatter_map() const {
  // @@protoc_insertion_point(field_get:recontaskparameter_pb.ReconTaskParameterPB.use_scatter_map)
  return _internal_use_scatter_map();
}
inline void ReconTaskParameterPB::_internal_set_use_scatter_map(bool value) {
  _has_bits_[0] |= 0x00020000u;
  use_scatter_map_ = value;
}
inline void ReconTaskParameterPB::set_use_scatter_map(bool value) {
  _internal_set_use_scatter_map(value);
  // @@protoc_insertion_point(field_set:recontaskparameter_pb.ReconTaskParameterPB.use_scatter_map)
}

// required int32 num_iters = 8;
inline bool ReconTaskParameterPB::_internal_has_num_iters() const {
  bool value = (_has_bits_[0] & 0x00000100u) != 0;
  return value;
}
inline bool ReconTaskParameterPB::has_num_iters() const {
  return _internal_has_num_iters();
}
inline void ReconTaskParameterPB::clear_num_iters() {
  num_iters_ = 0;
  _has_bits_[0] &= ~0x00000100u;
}
inline int32_t ReconTaskParameterPB::_internal_num_iters() const {
  return num_iters_;
}
inline int32_t ReconTaskParameterPB::num_iters() const {
  // @@protoc_insertion_point(field_get:recontaskparameter_pb.ReconTaskParameterPB.num_iters)
  return _internal_num_iters();
}
inline void ReconTaskParameterPB::_internal_set_num_iters(int32_t value) {
  _has_bits_[0] |= 0x00000100u;
  num_iters_ = value;
}
inline void ReconTaskParameterPB::set_num_iters(int32_t value) {
  _internal_set_num_iters(value);
  // @@protoc_insertion_point(field_set:recontaskparameter_pb.ReconTaskParameterPB.num_iters)
}

// required int32 num_dual_iters = 9;
inline bool ReconTaskParameterPB::_internal_has_num_dual_iters() const {
  bool value = (_has_bits_[0] & 0x00000200u) != 0;
  return value;
}
inline bool ReconTaskParameterPB::has_num_dual_iters() const {
  return _internal_has_num_dual_iters();
}
inline void ReconTaskParameterPB::clear_num_dual_iters() {
  num_dual_iters_ = 0;
  _has_bits_[0] &= ~0x00000200u;
}
inline int32_t ReconTaskParameterPB::_internal_num_dual_iters() const {
  return num_dual_iters_;
}
inline int32_t ReconTaskParameterPB::num_dual_iters() const {
  // @@protoc_insertion_point(field_get:recontaskparameter_pb.ReconTaskParameterPB.num_dual_iters)
  return _internal_num_dual_iters();
}
inline void ReconTaskParameterPB::_internal_set_num_dual_iters(int32_t value) {
  _has_bits_[0] |= 0x00000200u;
  num_dual_iters_ = value;
}
inline void ReconTaskParameterPB::set_num_dual_iters(int32_t value) {
  _internal_set_num_dual_iters(value);
  // @@protoc_insertion_point(field_set:recontaskparameter_pb.ReconTaskParameterPB.num_dual_iters)
}

// required double gamma = 10;
inline bool ReconTaskParameterPB::_internal_has_gamma() const {
  bool value = (_has_bits_[0] & 0x00000400u) != 0;
  return value;
}
inline bool ReconTaskParameterPB::has_gamma() const {
  return _internal_has_gamma();
}
inline void ReconTaskParameterPB::clear_gamma() {
  gamma_ = 0;
  _has_bits_[0] &= ~0x00000400u;
}
inline double ReconTaskParameterPB::_internal_gamma() const {
  return gamma_;
}
inline double ReconTaskParameterPB::gamma() const {
  // @@protoc_insertion_point(field_get:recontaskparameter_pb.ReconTaskParameterPB.gamma)
  return _internal_gamma();
}
inline void ReconTaskParameterPB::_internal_set_gamma(double value) {
  _has_bits_[0] |= 0x00000400u;
  gamma_ = value;
}
inline void ReconTaskParameterPB::set_gamma(double value) {
  _internal_set_gamma(value);
  // @@protoc_insertion_point(field_set:recontaskparameter_pb.ReconTaskParameterPB.gamma)
}

// required double lambda = 11;
inline bool ReconTaskParameterPB::_internal_has_lambda() const {
  bool value = (_has_bits_[0] & 0x00000800u) != 0;
  return value;
}
inline bool ReconTaskParameterPB::has_lambda() const {
  return _internal_has_lambda();
}
inline void ReconTaskParameterPB::clear_lambda() {
  lambda_ = 0;
  _has_bits_[0] &= ~0x00000800u;
}
inline double ReconTaskParameterPB::_internal_lambda() const {
  return lambda_;
}
inline double ReconTaskParameterPB::lambda() const {
  // @@protoc_insertion_point(field_get:recontaskparameter_pb.ReconTaskParameterPB.lambda)
  return _internal_lambda();
}
inline void ReconTaskParameterPB::_internal_set_lambda(double value) {
  _has_bits_[0] |= 0x00000800u;
  lambda_ = value;
}
inline void ReconTaskParameterPB::set_lambda(double value) {
  _internal_set_lambda(value);
  // @@protoc_insertion_point(field_set:recontaskparameter_pb.ReconTaskParameterPB.lambda)
}

// optional double coeff_scatter = 12;
inline bool ReconTaskParameterPB::_internal_has_coeff_scatter() const {
  bool value = (_has_bits_[0] & 0x00001000u) != 0;
  return value;
}
inline bool ReconTaskParameterPB::has_coeff_scatter() const {
  return _internal_has_coeff_scatter();
}
inline void ReconTaskParameterPB::clear_coeff_scatter() {
  coeff_scatter_ = 0;
  _has_bits_[0] &= ~0x00001000u;
}
inline double ReconTaskParameterPB::_internal_coeff_scatter() const {
  return coeff_scatter_;
}
inline double ReconTaskParameterPB::coeff_scatter() const {
  // @@protoc_insertion_point(field_get:recontaskparameter_pb.ReconTaskParameterPB.coeff_scatter)
  return _internal_coeff_scatter();
}
inline void ReconTaskParameterPB::_internal_set_coeff_scatter(double value) {
  _has_bits_[0] |= 0x00001000u;
  coeff_scatter_ = value;
}
inline void ReconTaskParameterPB::set_coeff_scatter(double value) {
  _internal_set_coeff_scatter(value);
  // @@protoc_insertion_point(field_set:recontaskparameter_pb.ReconTaskParameterPB.coeff_scatter)
}

// required string output_dir = 13;
inline bool ReconTaskParameterPB::_internal_has_output_dir() const {
  bool value = (_has_bits_[0] & 0x00000020u) != 0;
  return value;
}
inline bool ReconTaskParameterPB::has_output_dir() const {
  return _internal_has_output_dir();
}
inline void ReconTaskParameterPB::clear_output_dir() {
  output_dir_.ClearToEmpty();
  _has_bits_[0] &= ~0x00000020u;
}
inline const std::string& ReconTaskParameterPB::output_dir() const {
  // @@protoc_insertion_point(field_get:recontaskparameter_pb.ReconTaskParameterPB.output_dir)
  return _internal_output_dir();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void ReconTaskParameterPB::set_output_dir(ArgT0&& arg0, ArgT... args) {
 _has_bits_[0] |= 0x00000020u;
 output_dir_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:recontaskparameter_pb.ReconTaskParameterPB.output_dir)
}
inline std::string* ReconTaskParameterPB::mutable_output_dir() {
  std::string* _s = _internal_mutable_output_dir();
  // @@protoc_insertion_point(field_mutable:recontaskparameter_pb.ReconTaskParameterPB.output_dir)
  return _s;
}
inline const std::string& ReconTaskParameterPB::_internal_output_dir() const {
  return output_dir_.Get();
}
inline void ReconTaskParameterPB::_internal_set_output_dir(const std::string& value) {
  _has_bits_[0] |= 0x00000020u;
  output_dir_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* ReconTaskParameterPB::_internal_mutable_output_dir() {
  _has_bits_[0] |= 0x00000020u;
  return output_dir_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* ReconTaskParameterPB::release_output_dir() {
  // @@protoc_insertion_point(field_release:recontaskparameter_pb.ReconTaskParameterPB.output_dir)
  if (!_internal_has_output_dir()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000020u;
  auto* p = output_dir_.ReleaseNonDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (output_dir_.IsDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited())) {
    output_dir_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return p;
}
inline void ReconTaskParameterPB::set_allocated_output_dir(std::string* output_dir) {
  if (output_dir != nullptr) {
    _has_bits_[0] |= 0x00000020u;
  } else {
    _has_bits_[0] &= ~0x00000020u;
  }
  output_dir_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), output_dir,
      GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (output_dir_.IsDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited())) {
    output_dir_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:recontaskparameter_pb.ReconTaskParameterPB.output_dir)
}

// required .recontaskparameter_pb.ReconTaskParameterPB.IteratorType iterator = 14;
inline bool ReconTaskParameterPB::_internal_has_iterator() const {
  bool value = (_has_bits_[0] & 0x00002000u) != 0;
  return value;
}
inline bool ReconTaskParameterPB::has_iterator() const {
  return _internal_has_iterator();
}
inline void ReconTaskParameterPB::clear_iterator() {
  iterator_ = 0;
  _has_bits_[0] &= ~0x00002000u;
}
inline ::recontaskparameter_pb::ReconTaskParameterPB_IteratorType ReconTaskParameterPB::_internal_iterator() const {
  return static_cast< ::recontaskparameter_pb::ReconTaskParameterPB_IteratorType >(iterator_);
}
inline ::recontaskparameter_pb::ReconTaskParameterPB_IteratorType ReconTaskParameterPB::iterator() const {
  // @@protoc_insertion_point(field_get:recontaskparameter_pb.ReconTaskParameterPB.iterator)
  return _internal_iterator();
}
inline void ReconTaskParameterPB::_internal_set_iterator(::recontaskparameter_pb::ReconTaskParameterPB_IteratorType value) {
  assert(::recontaskparameter_pb::ReconTaskParameterPB_IteratorType_IsValid(value));
  _has_bits_[0] |= 0x00002000u;
  iterator_ = value;
}
inline void ReconTaskParameterPB::set_iterator(::recontaskparameter_pb::ReconTaskParameterPB_IteratorType value) {
  _internal_set_iterator(value);
  // @@protoc_insertion_point(field_set:recontaskparameter_pb.ReconTaskParameterPB.iterator)
}

// required .recontaskparameter_pb.ReconTaskParameterPB.FileFormat file_format = 15;
inline bool ReconTaskParameterPB::_internal_has_file_format() const {
  bool value = (_has_bits_[0] & 0x00004000u) != 0;
  return value;
}
inline bool ReconTaskParameterPB::has_file_format() const {
  return _internal_has_file_format();
}
inline void ReconTaskParameterPB::clear_file_format() {
  file_format_ = 0;
  _has_bits_[0] &= ~0x00004000u;
}
inline ::recontaskparameter_pb::ReconTaskParameterPB_FileFormat ReconTaskParameterPB::_internal_file_format() const {
  return static_cast< ::recontaskparameter_pb::ReconTaskParameterPB_FileFormat >(file_format_);
}
inline ::recontaskparameter_pb::ReconTaskParameterPB_FileFormat ReconTaskParameterPB::file_format() const {
  // @@protoc_insertion_point(field_get:recontaskparameter_pb.ReconTaskParameterPB.file_format)
  return _internal_file_format();
}
inline void ReconTaskParameterPB::_internal_set_file_format(::recontaskparameter_pb::ReconTaskParameterPB_FileFormat value) {
  assert(::recontaskparameter_pb::ReconTaskParameterPB_FileFormat_IsValid(value));
  _has_bits_[0] |= 0x00004000u;
  file_format_ = value;
}
inline void ReconTaskParameterPB::set_file_format(::recontaskparameter_pb::ReconTaskParameterPB_FileFormat value) {
  _internal_set_file_format(value);
  // @@protoc_insertion_point(field_set:recontaskparameter_pb.ReconTaskParameterPB.file_format)
}

// required int32 num_input_images = 16;
inline bool ReconTaskParameterPB::_internal_has_num_input_images() const {
  bool value = (_has_bits_[0] & 0x00008000u) != 0;
  return value;
}
inline bool ReconTaskParameterPB::has_num_input_images() const {
  return _internal_has_num_input_images();
}
inline void ReconTaskParameterPB::clear_num_input_images() {
  num_input_images_ = 0;
  _has_bits_[0] &= ~0x00008000u;
}
inline int32_t ReconTaskParameterPB::_internal_num_input_images() const {
  return num_input_images_;
}
inline int32_t ReconTaskParameterPB::num_input_images() const {
  // @@protoc_insertion_point(field_get:recontaskparameter_pb.ReconTaskParameterPB.num_input_images)
  return _internal_num_input_images();
}
inline void ReconTaskParameterPB::_internal_set_num_input_images(int32_t value) {
  _has_bits_[0] |= 0x00008000u;
  num_input_images_ = value;
}
inline void ReconTaskParameterPB::set_num_input_images(int32_t value) {
  _internal_set_num_input_images(value);
  // @@protoc_insertion_point(field_set:recontaskparameter_pb.ReconTaskParameterPB.num_input_images)
}

// required .recontaskparameter_pb.ReconTaskParameterPB.FileDataType file_data_type = 17;
inline bool ReconTaskParameterPB::_internal_has_file_data_type() const {
  bool value = (_has_bits_[0] & 0x08000000u) != 0;
  return value;
}
inline bool ReconTaskParameterPB::has_file_data_type() const {
  return _internal_has_file_data_type();
}
inline void ReconTaskParameterPB::clear_file_data_type() {
  file_data_type_ = 1;
  _has_bits_[0] &= ~0x08000000u;
}
inline ::recontaskparameter_pb::ReconTaskParameterPB_FileDataType ReconTaskParameterPB::_internal_file_data_type() const {
  return static_cast< ::recontaskparameter_pb::ReconTaskParameterPB_FileDataType >(file_data_type_);
}
inline ::recontaskparameter_pb::ReconTaskParameterPB_FileDataType ReconTaskParameterPB::file_data_type() const {
  // @@protoc_insertion_point(field_get:recontaskparameter_pb.ReconTaskParameterPB.file_data_type)
  return _internal_file_data_type();
}
inline void ReconTaskParameterPB::_internal_set_file_data_type(::recontaskparameter_pb::ReconTaskParameterPB_FileDataType value) {
  assert(::recontaskparameter_pb::ReconTaskParameterPB_FileDataType_IsValid(value));
  _has_bits_[0] |= 0x08000000u;
  file_data_type_ = value;
}
inline void ReconTaskParameterPB::set_file_data_type(::recontaskparameter_pb::ReconTaskParameterPB_FileDataType value) {
  _internal_set_file_data_type(value);
  // @@protoc_insertion_point(field_set:recontaskparameter_pb.ReconTaskParameterPB.file_data_type)
}

// required int32 index_sinogram = 18;
inline bool ReconTaskParameterPB::_internal_has_index_sinogram() const {
  bool value = (_has_bits_[0] & 0x00100000u) != 0;
  return value;
}
inline bool ReconTaskParameterPB::has_index_sinogram() const {
  return _internal_has_index_sinogram();
}
inline void ReconTaskParameterPB::clear_index_sinogram() {
  index_sinogram_ = 0;
  _has_bits_[0] &= ~0x00100000u;
}
inline int32_t ReconTaskParameterPB::_internal_index_sinogram() const {
  return index_sinogram_;
}
inline int32_t ReconTaskParameterPB::index_sinogram() const {
  // @@protoc_insertion_point(field_get:recontaskparameter_pb.ReconTaskParameterPB.index_sinogram)
  return _internal_index_sinogram();
}
inline void ReconTaskParameterPB::_internal_set_index_sinogram(int32_t value) {
  _has_bits_[0] |= 0x00100000u;
  index_sinogram_ = value;
}
inline void ReconTaskParameterPB::set_index_sinogram(int32_t value) {
  _internal_set_index_sinogram(value);
  // @@protoc_insertion_point(field_set:recontaskparameter_pb.ReconTaskParameterPB.index_sinogram)
}

// required int32 index_projection = 19;
inline bool ReconTaskParameterPB::_internal_has_index_projection() const {
  bool value = (_has_bits_[0] & 0x00200000u) != 0;
  return value;
}
inline bool ReconTaskParameterPB::has_index_projection() const {
  return _internal_has_index_projection();
}
inline void ReconTaskParameterPB::clear_index_projection() {
  index_projection_ = 0;
  _has_bits_[0] &= ~0x00200000u;
}
inline int32_t ReconTaskParameterPB::_internal_index_projection() const {
  return index_projection_;
}
inline int32_t ReconTaskParameterPB::index_projection() const {
  // @@protoc_insertion_point(field_get:recontaskparameter_pb.ReconTaskParameterPB.index_projection)
  return _internal_index_projection();
}
inline void ReconTaskParameterPB::_internal_set_index_projection(int32_t value) {
  _has_bits_[0] |= 0x00200000u;
  index_projection_ = value;
}
inline void ReconTaskParameterPB::set_index_projection(int32_t value) {
  _internal_set_index_projection(value);
  // @@protoc_insertion_point(field_set:recontaskparameter_pb.ReconTaskParameterPB.index_projection)
}

// required int32 num_detectors = 20;
inline bool ReconTaskParameterPB::_internal_has_num_detectors() const {
  bool value = (_has_bits_[0] & 0x00400000u) != 0;
  return value;
}
inline bool ReconTaskParameterPB::has_num_detectors() const {
  return _internal_has_num_detectors();
}
inline void ReconTaskParameterPB::clear_num_detectors() {
  num_detectors_ = 0;
  _has_bits_[0] &= ~0x00400000u;
}
inline int32_t ReconTaskParameterPB::_internal_num_detectors() const {
  return num_detectors_;
}
inline int32_t ReconTaskParameterPB::num_detectors() const {
  // @@protoc_insertion_point(field_get:recontaskparameter_pb.ReconTaskParameterPB.num_detectors)
  return _internal_num_detectors();
}
inline void ReconTaskParameterPB::_internal_set_num_detectors(int32_t value) {
  _has_bits_[0] |= 0x00400000u;
  num_detectors_ = value;
}
inline void ReconTaskParameterPB::set_num_detectors(int32_t value) {
  _internal_set_num_detectors(value);
  // @@protoc_insertion_point(field_set:recontaskparameter_pb.ReconTaskParameterPB.num_detectors)
}

// required int32 num_angles = 21;
inline bool ReconTaskParameterPB::_internal_has_num_angles() const {
  bool value = (_has_bits_[0] & 0x00800000u) != 0;
  return value;
}
inline bool ReconTaskParameterPB::has_num_angles() const {
  return _internal_has_num_angles();
}
inline void ReconTaskParameterPB::clear_num_angles() {
  num_angles_ = 0;
  _has_bits_[0] &= ~0x00800000u;
}
inline int32_t ReconTaskParameterPB::_internal_num_angles() const {
  return num_angles_;
}
inline int32_t ReconTaskParameterPB::num_angles() const {
  // @@protoc_insertion_point(field_get:recontaskparameter_pb.ReconTaskParameterPB.num_angles)
  return _internal_num_angles();
}
inline void ReconTaskParameterPB::_internal_set_num_angles(int32_t value) {
  _has_bits_[0] |= 0x00800000u;
  num_angles_ = value;
}
inline void ReconTaskParameterPB::set_num_angles(int32_t value) {
  _internal_set_num_angles(value);
  // @@protoc_insertion_point(field_set:recontaskparameter_pb.ReconTaskParameterPB.num_angles)
}

// required int32 num_slices = 22;
inline bool ReconTaskParameterPB::_internal_has_num_slices() const {
  bool value = (_has_bits_[0] & 0x01000000u) != 0;
  return value;
}
inline bool ReconTaskParameterPB::has_num_slices() const {
  return _internal_has_num_slices();
}
inline void ReconTaskParameterPB::clear_num_slices() {
  num_slices_ = 0;
  _has_bits_[0] &= ~0x01000000u;
}
inline int32_t ReconTaskParameterPB::_internal_num_slices() const {
  return num_slices_;
}
inline int32_t ReconTaskParameterPB::num_slices() const {
  // @@protoc_insertion_point(field_get:recontaskparameter_pb.ReconTaskParameterPB.num_slices)
  return _internal_num_slices();
}
inline void ReconTaskParameterPB::_internal_set_num_slices(int32_t value) {
  _has_bits_[0] |= 0x01000000u;
  num_slices_ = value;
}
inline void ReconTaskParameterPB::set_num_slices(int32_t value) {
  _internal_set_num_slices(value);
  // @@protoc_insertion_point(field_set:recontaskparameter_pb.ReconTaskParameterPB.num_slices)
}

// required int32 num_results = 23;
inline bool ReconTaskParameterPB::_internal_has_num_results() const {
  bool value = (_has_bits_[0] & 0x02000000u) != 0;
  return value;
}
inline bool ReconTaskParameterPB::has_num_results() const {
  return _internal_has_num_results();
}
inline void ReconTaskParameterPB::clear_num_results() {
  num_results_ = 0;
  _has_bits_[0] &= ~0x02000000u;
}
inline int32_t ReconTaskParameterPB::_internal_num_results() const {
  return num_results_;
}
inline int32_t ReconTaskParameterPB::num_results() const {
  // @@protoc_insertion_point(field_get:recontaskparameter_pb.ReconTaskParameterPB.num_results)
  return _internal_num_results();
}
inline void ReconTaskParameterPB::_internal_set_num_results(int32_t value) {
  _has_bits_[0] |= 0x02000000u;
  num_results_ = value;
}
inline void ReconTaskParameterPB::set_num_results(int32_t value) {
  _internal_set_num_results(value);
  // @@protoc_insertion_point(field_set:recontaskparameter_pb.ReconTaskParameterPB.num_results)
}

// repeated double sinogram_data = 24;
inline int ReconTaskParameterPB::_internal_sinogram_data_size() const {
  return sinogram_data_.size();
}
inline int ReconTaskParameterPB::sinogram_data_size() const {
  return _internal_sinogram_data_size();
}
inline void ReconTaskParameterPB::clear_sinogram_data() {
  sinogram_data_.Clear();
}
inline double ReconTaskParameterPB::_internal_sinogram_data(int index) const {
  return sinogram_data_.Get(index);
}
inline double ReconTaskParameterPB::sinogram_data(int index) const {
  // @@protoc_insertion_point(field_get:recontaskparameter_pb.ReconTaskParameterPB.sinogram_data)
  return _internal_sinogram_data(index);
}
inline void ReconTaskParameterPB::set_sinogram_data(int index, double value) {
  sinogram_data_.Set(index, value);
  // @@protoc_insertion_point(field_set:recontaskparameter_pb.ReconTaskParameterPB.sinogram_data)
}
inline void ReconTaskParameterPB::_internal_add_sinogram_data(double value) {
  sinogram_data_.Add(value);
}
inline void ReconTaskParameterPB::add_sinogram_data(double value) {
  _internal_add_sinogram_data(value);
  // @@protoc_insertion_point(field_add:recontaskparameter_pb.ReconTaskParameterPB.sinogram_data)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >&
ReconTaskParameterPB::_internal_sinogram_data() const {
  return sinogram_data_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >&
ReconTaskParameterPB::sinogram_data() const {
  // @@protoc_insertion_point(field_list:recontaskparameter_pb.ReconTaskParameterPB.sinogram_data)
  return _internal_sinogram_data();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >*
ReconTaskParameterPB::_internal_mutable_sinogram_data() {
  return &sinogram_data_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >*
ReconTaskParameterPB::mutable_sinogram_data() {
  // @@protoc_insertion_point(field_mutable_list:recontaskparameter_pb.ReconTaskParameterPB.sinogram_data)
  return _internal_mutable_sinogram_data();
}

// repeated double restored_sinogram_data = 25;
inline int ReconTaskParameterPB::_internal_restored_sinogram_data_size() const {
  return restored_sinogram_data_.size();
}
inline int ReconTaskParameterPB::restored_sinogram_data_size() const {
  return _internal_restored_sinogram_data_size();
}
inline void ReconTaskParameterPB::clear_restored_sinogram_data() {
  restored_sinogram_data_.Clear();
}
inline double ReconTaskParameterPB::_internal_restored_sinogram_data(int index) const {
  return restored_sinogram_data_.Get(index);
}
inline double ReconTaskParameterPB::restored_sinogram_data(int index) const {
  // @@protoc_insertion_point(field_get:recontaskparameter_pb.ReconTaskParameterPB.restored_sinogram_data)
  return _internal_restored_sinogram_data(index);
}
inline void ReconTaskParameterPB::set_restored_sinogram_data(int index, double value) {
  restored_sinogram_data_.Set(index, value);
  // @@protoc_insertion_point(field_set:recontaskparameter_pb.ReconTaskParameterPB.restored_sinogram_data)
}
inline void ReconTaskParameterPB::_internal_add_restored_sinogram_data(double value) {
  restored_sinogram_data_.Add(value);
}
inline void ReconTaskParameterPB::add_restored_sinogram_data(double value) {
  _internal_add_restored_sinogram_data(value);
  // @@protoc_insertion_point(field_add:recontaskparameter_pb.ReconTaskParameterPB.restored_sinogram_data)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >&
ReconTaskParameterPB::_internal_restored_sinogram_data() const {
  return restored_sinogram_data_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >&
ReconTaskParameterPB::restored_sinogram_data() const {
  // @@protoc_insertion_point(field_list:recontaskparameter_pb.ReconTaskParameterPB.restored_sinogram_data)
  return _internal_restored_sinogram_data();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >*
ReconTaskParameterPB::_internal_mutable_restored_sinogram_data() {
  return &restored_sinogram_data_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >*
ReconTaskParameterPB::mutable_restored_sinogram_data() {
  // @@protoc_insertion_point(field_mutable_list:recontaskparameter_pb.ReconTaskParameterPB.restored_sinogram_data)
  return _internal_mutable_restored_sinogram_data();
}

// repeated double reconstructed_tomographs_data = 26;
inline int ReconTaskParameterPB::_internal_reconstructed_tomographs_data_size() const {
  return reconstructed_tomographs_data_.size();
}
inline int ReconTaskParameterPB::reconstructed_tomographs_data_size() const {
  return _internal_reconstructed_tomographs_data_size();
}
inline void ReconTaskParameterPB::clear_reconstructed_tomographs_data() {
  reconstructed_tomographs_data_.Clear();
}
inline double ReconTaskParameterPB::_internal_reconstructed_tomographs_data(int index) const {
  return reconstructed_tomographs_data_.Get(index);
}
inline double ReconTaskParameterPB::reconstructed_tomographs_data(int index) const {
  // @@protoc_insertion_point(field_get:recontaskparameter_pb.ReconTaskParameterPB.reconstructed_tomographs_data)
  return _internal_reconstructed_tomographs_data(index);
}
inline void ReconTaskParameterPB::set_reconstructed_tomographs_data(int index, double value) {
  reconstructed_tomographs_data_.Set(index, value);
  // @@protoc_insertion_point(field_set:recontaskparameter_pb.ReconTaskParameterPB.reconstructed_tomographs_data)
}
inline void ReconTaskParameterPB::_internal_add_reconstructed_tomographs_data(double value) {
  reconstructed_tomographs_data_.Add(value);
}
inline void ReconTaskParameterPB::add_reconstructed_tomographs_data(double value) {
  _internal_add_reconstructed_tomographs_data(value);
  // @@protoc_insertion_point(field_add:recontaskparameter_pb.ReconTaskParameterPB.reconstructed_tomographs_data)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >&
ReconTaskParameterPB::_internal_reconstructed_tomographs_data() const {
  return reconstructed_tomographs_data_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >&
ReconTaskParameterPB::reconstructed_tomographs_data() const {
  // @@protoc_insertion_point(field_list:recontaskparameter_pb.ReconTaskParameterPB.reconstructed_tomographs_data)
  return _internal_reconstructed_tomographs_data();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >*
ReconTaskParameterPB::_internal_mutable_reconstructed_tomographs_data() {
  return &reconstructed_tomographs_data_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >*
ReconTaskParameterPB::mutable_reconstructed_tomographs_data() {
  // @@protoc_insertion_point(field_mutable_list:recontaskparameter_pb.ReconTaskParameterPB.reconstructed_tomographs_data)
  return _internal_mutable_reconstructed_tomographs_data();
}

// required bool done = 27;
inline bool ReconTaskParameterPB::_internal_has_done() const {
  bool value = (_has_bits_[0] & 0x00040000u) != 0;
  return value;
}
inline bool ReconTaskParameterPB::has_done() const {
  return _internal_has_done();
}
inline void ReconTaskParameterPB::clear_done() {
  done_ = false;
  _has_bits_[0] &= ~0x00040000u;
}
inline bool ReconTaskParameterPB::_internal_done() const {
  return done_;
}
inline bool ReconTaskParameterPB::done() const {
  // @@protoc_insertion_point(field_get:recontaskparameter_pb.ReconTaskParameterPB.done)
  return _internal_done();
}
inline void ReconTaskParameterPB::_internal_set_done(bool value) {
  _has_bits_[0] |= 0x00040000u;
  done_ = value;
}
inline void ReconTaskParameterPB::set_done(bool value) {
  _internal_set_done(value);
  // @@protoc_insertion_point(field_set:recontaskparameter_pb.ReconTaskParameterPB.done)
}

// required bool loaded = 28;
inline bool ReconTaskParameterPB::_internal_has_loaded() const {
  bool value = (_has_bits_[0] & 0x00080000u) != 0;
  return value;
}
inline bool ReconTaskParameterPB::has_loaded() const {
  return _internal_has_loaded();
}
inline void ReconTaskParameterPB::clear_loaded() {
  loaded_ = false;
  _has_bits_[0] &= ~0x00080000u;
}
inline bool ReconTaskParameterPB::_internal_loaded() const {
  return loaded_;
}
inline bool ReconTaskParameterPB::loaded() const {
  // @@protoc_insertion_point(field_get:recontaskparameter_pb.ReconTaskParameterPB.loaded)
  return _internal_loaded();
}
inline void ReconTaskParameterPB::_internal_set_loaded(bool value) {
  _has_bits_[0] |= 0x00080000u;
  loaded_ = value;
}
inline void ReconTaskParameterPB::set_loaded(bool value) {
  _internal_set_loaded(value);
  // @@protoc_insertion_point(field_set:recontaskparameter_pb.ReconTaskParameterPB.loaded)
}

// required string path_model = 29;
inline bool ReconTaskParameterPB::_internal_has_path_model() const {
  bool value = (_has_bits_[0] & 0x00000040u) != 0;
  return value;
}
inline bool ReconTaskParameterPB::has_path_model() const {
  return _internal_has_path_model();
}
inline void ReconTaskParameterPB::clear_path_model() {
  path_model_.ClearToEmpty();
  _has_bits_[0] &= ~0x00000040u;
}
inline const std::string& ReconTaskParameterPB::path_model() const {
  // @@protoc_insertion_point(field_get:recontaskparameter_pb.ReconTaskParameterPB.path_model)
  return _internal_path_model();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void ReconTaskParameterPB::set_path_model(ArgT0&& arg0, ArgT... args) {
 _has_bits_[0] |= 0x00000040u;
 path_model_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:recontaskparameter_pb.ReconTaskParameterPB.path_model)
}
inline std::string* ReconTaskParameterPB::mutable_path_model() {
  std::string* _s = _internal_mutable_path_model();
  // @@protoc_insertion_point(field_mutable:recontaskparameter_pb.ReconTaskParameterPB.path_model)
  return _s;
}
inline const std::string& ReconTaskParameterPB::_internal_path_model() const {
  return path_model_.Get();
}
inline void ReconTaskParameterPB::_internal_set_path_model(const std::string& value) {
  _has_bits_[0] |= 0x00000040u;
  path_model_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* ReconTaskParameterPB::_internal_mutable_path_model() {
  _has_bits_[0] |= 0x00000040u;
  return path_model_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* ReconTaskParameterPB::release_path_model() {
  // @@protoc_insertion_point(field_release:recontaskparameter_pb.ReconTaskParameterPB.path_model)
  if (!_internal_has_path_model()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000040u;
  auto* p = path_model_.ReleaseNonDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (path_model_.IsDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited())) {
    path_model_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return p;
}
inline void ReconTaskParameterPB::set_allocated_path_model(std::string* path_model) {
  if (path_model != nullptr) {
    _has_bits_[0] |= 0x00000040u;
  } else {
    _has_bits_[0] &= ~0x00000040u;
  }
  path_model_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), path_model,
      GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (path_model_.IsDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited())) {
    path_model_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:recontaskparameter_pb.ReconTaskParameterPB.path_model)
}

// required string sinogram_info = 30;
inline bool ReconTaskParameterPB::_internal_has_sinogram_info() const {
  bool value = (_has_bits_[0] & 0x00000080u) != 0;
  return value;
}
inline bool ReconTaskParameterPB::has_sinogram_info() const {
  return _internal_has_sinogram_info();
}
inline void ReconTaskParameterPB::clear_sinogram_info() {
  sinogram_info_.ClearToEmpty();
  _has_bits_[0] &= ~0x00000080u;
}
inline const std::string& ReconTaskParameterPB::sinogram_info() const {
  // @@protoc_insertion_point(field_get:recontaskparameter_pb.ReconTaskParameterPB.sinogram_info)
  return _internal_sinogram_info();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void ReconTaskParameterPB::set_sinogram_info(ArgT0&& arg0, ArgT... args) {
 _has_bits_[0] |= 0x00000080u;
 sinogram_info_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:recontaskparameter_pb.ReconTaskParameterPB.sinogram_info)
}
inline std::string* ReconTaskParameterPB::mutable_sinogram_info() {
  std::string* _s = _internal_mutable_sinogram_info();
  // @@protoc_insertion_point(field_mutable:recontaskparameter_pb.ReconTaskParameterPB.sinogram_info)
  return _s;
}
inline const std::string& ReconTaskParameterPB::_internal_sinogram_info() const {
  return sinogram_info_.Get();
}
inline void ReconTaskParameterPB::_internal_set_sinogram_info(const std::string& value) {
  _has_bits_[0] |= 0x00000080u;
  sinogram_info_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* ReconTaskParameterPB::_internal_mutable_sinogram_info() {
  _has_bits_[0] |= 0x00000080u;
  return sinogram_info_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* ReconTaskParameterPB::release_sinogram_info() {
  // @@protoc_insertion_point(field_release:recontaskparameter_pb.ReconTaskParameterPB.sinogram_info)
  if (!_internal_has_sinogram_info()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000080u;
  auto* p = sinogram_info_.ReleaseNonDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (sinogram_info_.IsDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited())) {
    sinogram_info_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return p;
}
inline void ReconTaskParameterPB::set_allocated_sinogram_info(std::string* sinogram_info) {
  if (sinogram_info != nullptr) {
    _has_bits_[0] |= 0x00000080u;
  } else {
    _has_bits_[0] &= ~0x00000080u;
  }
  sinogram_info_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), sinogram_info,
      GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (sinogram_info_.IsDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited())) {
    sinogram_info_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:recontaskparameter_pb.ReconTaskParameterPB.sinogram_info)
}

// required int32 resolution = 31;
inline bool ReconTaskParameterPB::_internal_has_resolution() const {
  bool value = (_has_bits_[0] & 0x04000000u) != 0;
  return value;
}
inline bool ReconTaskParameterPB::has_resolution() const {
  return _internal_has_resolution();
}
inline void ReconTaskParameterPB::clear_resolution() {
  resolution_ = 0;
  _has_bits_[0] &= ~0x04000000u;
}
inline int32_t ReconTaskParameterPB::_internal_resolution() const {
  return resolution_;
}
inline int32_t ReconTaskParameterPB::resolution() const {
  // @@protoc_insertion_point(field_get:recontaskparameter_pb.ReconTaskParameterPB.resolution)
  return _internal_resolution();
}
inline void ReconTaskParameterPB::_internal_set_resolution(int32_t value) {
  _has_bits_[0] |= 0x04000000u;
  resolution_ = value;
}
inline void ReconTaskParameterPB::set_resolution(int32_t value) {
  _internal_set_resolution(value);
  // @@protoc_insertion_point(field_set:recontaskparameter_pb.ReconTaskParameterPB.resolution)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace recontaskparameter_pb

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::recontaskparameter_pb::ReconTaskParameterPB_IteratorType> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::recontaskparameter_pb::ReconTaskParameterPB_IteratorType>() {
  return ::recontaskparameter_pb::ReconTaskParameterPB_IteratorType_descriptor();
}
template <> struct is_proto_enum< ::recontaskparameter_pb::ReconTaskParameterPB_FileFormat> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::recontaskparameter_pb::ReconTaskParameterPB_FileFormat>() {
  return ::recontaskparameter_pb::ReconTaskParameterPB_FileFormat_descriptor();
}
template <> struct is_proto_enum< ::recontaskparameter_pb::ReconTaskParameterPB_FileDataType> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::recontaskparameter_pb::ReconTaskParameterPB_FileDataType>() {
  return ::recontaskparameter_pb::ReconTaskParameterPB_FileDataType_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_recontaskparameter_2eproto
