// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: recontaskparameter.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_recontaskparameter_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_recontaskparameter_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3017000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3017002 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_recontaskparameter_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_recontaskparameter_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_recontaskparameter_2eproto;
namespace recontaskparameter_pb {
class ReconTaskParameterPB;
struct ReconTaskParameterPBDefaultTypeInternal;
extern ReconTaskParameterPBDefaultTypeInternal _ReconTaskParameterPB_default_instance_;
}  // namespace recontaskparameter_pb
PROTOBUF_NAMESPACE_OPEN
template<> ::recontaskparameter_pb::ReconTaskParameterPB* Arena::CreateMaybeMessage<::recontaskparameter_pb::ReconTaskParameterPB>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace recontaskparameter_pb {

enum ReconTaskParameterPB_IteratorType : int {
  ReconTaskParameterPB_IteratorType_MLEM = 0,
  ReconTaskParameterPB_IteratorType_EM_Tikhonov = 1,
  ReconTaskParameterPB_IteratorType_PAPA_2DWavelet = 2,
  ReconTaskParameterPB_IteratorType_PAPA_Cont = 3,
  ReconTaskParameterPB_IteratorType_PAPA_Cont_TV = 4,
  ReconTaskParameterPB_IteratorType_PAPA_Cont_Wavelet = 5,
  ReconTaskParameterPB_IteratorType_PAPA_Dynamic = 6,
  ReconTaskParameterPB_IteratorType_PAPA_TV = 7
};
bool ReconTaskParameterPB_IteratorType_IsValid(int value);
constexpr ReconTaskParameterPB_IteratorType ReconTaskParameterPB_IteratorType_IteratorType_MIN = ReconTaskParameterPB_IteratorType_MLEM;
constexpr ReconTaskParameterPB_IteratorType ReconTaskParameterPB_IteratorType_IteratorType_MAX = ReconTaskParameterPB_IteratorType_PAPA_TV;
constexpr int ReconTaskParameterPB_IteratorType_IteratorType_ARRAYSIZE = ReconTaskParameterPB_IteratorType_IteratorType_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ReconTaskParameterPB_IteratorType_descriptor();
template<typename T>
inline const std::string& ReconTaskParameterPB_IteratorType_Name(T enum_t_value) {
  static_assert(::std::is_same<T, ReconTaskParameterPB_IteratorType>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function ReconTaskParameterPB_IteratorType_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    ReconTaskParameterPB_IteratorType_descriptor(), enum_t_value);
}
inline bool ReconTaskParameterPB_IteratorType_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, ReconTaskParameterPB_IteratorType* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<ReconTaskParameterPB_IteratorType>(
    ReconTaskParameterPB_IteratorType_descriptor(), name, value);
}
// ===================================================================

class ReconTaskParameterPB final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:recontaskparameter_pb.ReconTaskParameterPB) */ {
 public:
  inline ReconTaskParameterPB() : ReconTaskParameterPB(nullptr) {}
  ~ReconTaskParameterPB() override;
  explicit constexpr ReconTaskParameterPB(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ReconTaskParameterPB(const ReconTaskParameterPB& from);
  ReconTaskParameterPB(ReconTaskParameterPB&& from) noexcept
    : ReconTaskParameterPB() {
    *this = ::std::move(from);
  }

  inline ReconTaskParameterPB& operator=(const ReconTaskParameterPB& from) {
    CopyFrom(from);
    return *this;
  }
  inline ReconTaskParameterPB& operator=(ReconTaskParameterPB&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ReconTaskParameterPB& default_instance() {
    return *internal_default_instance();
  }
  static inline const ReconTaskParameterPB* internal_default_instance() {
    return reinterpret_cast<const ReconTaskParameterPB*>(
               &_ReconTaskParameterPB_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(ReconTaskParameterPB& a, ReconTaskParameterPB& b) {
    a.Swap(&b);
  }
  inline void Swap(ReconTaskParameterPB* other) {
    if (other == this) return;
    if (GetOwningArena() == other->GetOwningArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ReconTaskParameterPB* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline ReconTaskParameterPB* New() const final {
    return new ReconTaskParameterPB();
  }

  ReconTaskParameterPB* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<ReconTaskParameterPB>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const ReconTaskParameterPB& from);
  void MergeFrom(const ReconTaskParameterPB& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ReconTaskParameterPB* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "recontaskparameter_pb.ReconTaskParameterPB";
  }
  protected:
  explicit ReconTaskParameterPB(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  typedef ReconTaskParameterPB_IteratorType IteratorType;
  static constexpr IteratorType MLEM =
    ReconTaskParameterPB_IteratorType_MLEM;
  static constexpr IteratorType EM_Tikhonov =
    ReconTaskParameterPB_IteratorType_EM_Tikhonov;
  static constexpr IteratorType PAPA_2DWavelet =
    ReconTaskParameterPB_IteratorType_PAPA_2DWavelet;
  static constexpr IteratorType PAPA_Cont =
    ReconTaskParameterPB_IteratorType_PAPA_Cont;
  static constexpr IteratorType PAPA_Cont_TV =
    ReconTaskParameterPB_IteratorType_PAPA_Cont_TV;
  static constexpr IteratorType PAPA_Cont_Wavelet =
    ReconTaskParameterPB_IteratorType_PAPA_Cont_Wavelet;
  static constexpr IteratorType PAPA_Dynamic =
    ReconTaskParameterPB_IteratorType_PAPA_Dynamic;
  static constexpr IteratorType PAPA_TV =
    ReconTaskParameterPB_IteratorType_PAPA_TV;
  static inline bool IteratorType_IsValid(int value) {
    return ReconTaskParameterPB_IteratorType_IsValid(value);
  }
  static constexpr IteratorType IteratorType_MIN =
    ReconTaskParameterPB_IteratorType_IteratorType_MIN;
  static constexpr IteratorType IteratorType_MAX =
    ReconTaskParameterPB_IteratorType_IteratorType_MAX;
  static constexpr int IteratorType_ARRAYSIZE =
    ReconTaskParameterPB_IteratorType_IteratorType_ARRAYSIZE;
  static inline const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor*
  IteratorType_descriptor() {
    return ReconTaskParameterPB_IteratorType_descriptor();
  }
  template<typename T>
  static inline const std::string& IteratorType_Name(T enum_t_value) {
    static_assert(::std::is_same<T, IteratorType>::value ||
      ::std::is_integral<T>::value,
      "Incorrect type passed to function IteratorType_Name.");
    return ReconTaskParameterPB_IteratorType_Name(enum_t_value);
  }
  static inline bool IteratorType_Parse(::PROTOBUF_NAMESPACE_ID::ConstStringParam name,
      IteratorType* value) {
    return ReconTaskParameterPB_IteratorType_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  enum : int {
    kTaskNameFieldNumber = 1,
    kPathSysmatFieldNumber = 2,
    kPathSinogdramFieldNumber = 3,
    kPathScatterMapFieldNumber = 4,
    kPathMuMapFieldNumber = 5,
    kOutputDirFieldNumber = 13,
    kUseNnFieldNumber = 6,
    kUseScatterMapFieldNumber = 7,
    kNumItersFieldNumber = 8,
    kGammaFieldNumber = 10,
    kLambdaFieldNumber = 11,
    kNumDualItersFieldNumber = 9,
    kIteratorFieldNumber = 14,
    kScatterCoeffFieldNumber = 12,
  };
  // required string task_name = 1;
  bool has_task_name() const;
  private:
  bool _internal_has_task_name() const;
  public:
  void clear_task_name();
  const std::string& task_name() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_task_name(ArgT0&& arg0, ArgT... args);
  std::string* mutable_task_name();
  PROTOBUF_FUTURE_MUST_USE_RESULT std::string* release_task_name();
  void set_allocated_task_name(std::string* task_name);
  private:
  const std::string& _internal_task_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_task_name(const std::string& value);
  std::string* _internal_mutable_task_name();
  public:

  // required string path_sysmat = 2;
  bool has_path_sysmat() const;
  private:
  bool _internal_has_path_sysmat() const;
  public:
  void clear_path_sysmat();
  const std::string& path_sysmat() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_path_sysmat(ArgT0&& arg0, ArgT... args);
  std::string* mutable_path_sysmat();
  PROTOBUF_FUTURE_MUST_USE_RESULT std::string* release_path_sysmat();
  void set_allocated_path_sysmat(std::string* path_sysmat);
  private:
  const std::string& _internal_path_sysmat() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_path_sysmat(const std::string& value);
  std::string* _internal_mutable_path_sysmat();
  public:

  // required string path_sinogdram = 3;
  bool has_path_sinogdram() const;
  private:
  bool _internal_has_path_sinogdram() const;
  public:
  void clear_path_sinogdram();
  const std::string& path_sinogdram() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_path_sinogdram(ArgT0&& arg0, ArgT... args);
  std::string* mutable_path_sinogdram();
  PROTOBUF_FUTURE_MUST_USE_RESULT std::string* release_path_sinogdram();
  void set_allocated_path_sinogdram(std::string* path_sinogdram);
  private:
  const std::string& _internal_path_sinogdram() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_path_sinogdram(const std::string& value);
  std::string* _internal_mutable_path_sinogdram();
  public:

  // optional string path_scatter_map = 4;
  bool has_path_scatter_map() const;
  private:
  bool _internal_has_path_scatter_map() const;
  public:
  void clear_path_scatter_map();
  const std::string& path_scatter_map() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_path_scatter_map(ArgT0&& arg0, ArgT... args);
  std::string* mutable_path_scatter_map();
  PROTOBUF_FUTURE_MUST_USE_RESULT std::string* release_path_scatter_map();
  void set_allocated_path_scatter_map(std::string* path_scatter_map);
  private:
  const std::string& _internal_path_scatter_map() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_path_scatter_map(const std::string& value);
  std::string* _internal_mutable_path_scatter_map();
  public:

  // optional string path_mu_map = 5;
  bool has_path_mu_map() const;
  private:
  bool _internal_has_path_mu_map() const;
  public:
  void clear_path_mu_map();
  const std::string& path_mu_map() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_path_mu_map(ArgT0&& arg0, ArgT... args);
  std::string* mutable_path_mu_map();
  PROTOBUF_FUTURE_MUST_USE_RESULT std::string* release_path_mu_map();
  void set_allocated_path_mu_map(std::string* path_mu_map);
  private:
  const std::string& _internal_path_mu_map() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_path_mu_map(const std::string& value);
  std::string* _internal_mutable_path_mu_map();
  public:

  // required string output_dir = 13;
  bool has_output_dir() const;
  private:
  bool _internal_has_output_dir() const;
  public:
  void clear_output_dir();
  const std::string& output_dir() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_output_dir(ArgT0&& arg0, ArgT... args);
  std::string* mutable_output_dir();
  PROTOBUF_FUTURE_MUST_USE_RESULT std::string* release_output_dir();
  void set_allocated_output_dir(std::string* output_dir);
  private:
  const std::string& _internal_output_dir() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_output_dir(const std::string& value);
  std::string* _internal_mutable_output_dir();
  public:

  // required bool use_nn = 6;
  bool has_use_nn() const;
  private:
  bool _internal_has_use_nn() const;
  public:
  void clear_use_nn();
  bool use_nn() const;
  void set_use_nn(bool value);
  private:
  bool _internal_use_nn() const;
  void _internal_set_use_nn(bool value);
  public:

  // required bool use_scatter_map = 7;
  bool has_use_scatter_map() const;
  private:
  bool _internal_has_use_scatter_map() const;
  public:
  void clear_use_scatter_map();
  bool use_scatter_map() const;
  void set_use_scatter_map(bool value);
  private:
  bool _internal_use_scatter_map() const;
  void _internal_set_use_scatter_map(bool value);
  public:

  // required int32 num_iters = 8;
  bool has_num_iters() const;
  private:
  bool _internal_has_num_iters() const;
  public:
  void clear_num_iters();
  ::PROTOBUF_NAMESPACE_ID::int32 num_iters() const;
  void set_num_iters(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_num_iters() const;
  void _internal_set_num_iters(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // required double gamma = 10;
  bool has_gamma() const;
  private:
  bool _internal_has_gamma() const;
  public:
  void clear_gamma();
  double gamma() const;
  void set_gamma(double value);
  private:
  double _internal_gamma() const;
  void _internal_set_gamma(double value);
  public:

  // required double lambda = 11;
  bool has_lambda() const;
  private:
  bool _internal_has_lambda() const;
  public:
  void clear_lambda();
  double lambda() const;
  void set_lambda(double value);
  private:
  double _internal_lambda() const;
  void _internal_set_lambda(double value);
  public:

  // required int32 num_dual_iters = 9;
  bool has_num_dual_iters() const;
  private:
  bool _internal_has_num_dual_iters() const;
  public:
  void clear_num_dual_iters();
  ::PROTOBUF_NAMESPACE_ID::int32 num_dual_iters() const;
  void set_num_dual_iters(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_num_dual_iters() const;
  void _internal_set_num_dual_iters(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // required .recontaskparameter_pb.ReconTaskParameterPB.IteratorType iterator = 14;
  bool has_iterator() const;
  private:
  bool _internal_has_iterator() const;
  public:
  void clear_iterator();
  ::recontaskparameter_pb::ReconTaskParameterPB_IteratorType iterator() const;
  void set_iterator(::recontaskparameter_pb::ReconTaskParameterPB_IteratorType value);
  private:
  ::recontaskparameter_pb::ReconTaskParameterPB_IteratorType _internal_iterator() const;
  void _internal_set_iterator(::recontaskparameter_pb::ReconTaskParameterPB_IteratorType value);
  public:

  // optional double scatter_coeff = 12;
  bool has_scatter_coeff() const;
  private:
  bool _internal_has_scatter_coeff() const;
  public:
  void clear_scatter_coeff();
  double scatter_coeff() const;
  void set_scatter_coeff(double value);
  private:
  double _internal_scatter_coeff() const;
  void _internal_set_scatter_coeff(double value);
  public:

  // @@protoc_insertion_point(class_scope:recontaskparameter_pb.ReconTaskParameterPB)
 private:
  class _Internal;

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr task_name_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr path_sysmat_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr path_sinogdram_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr path_scatter_map_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr path_mu_map_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr output_dir_;
  bool use_nn_;
  bool use_scatter_map_;
  ::PROTOBUF_NAMESPACE_ID::int32 num_iters_;
  double gamma_;
  double lambda_;
  ::PROTOBUF_NAMESPACE_ID::int32 num_dual_iters_;
  int iterator_;
  double scatter_coeff_;
  friend struct ::TableStruct_recontaskparameter_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// ReconTaskParameterPB

// required string task_name = 1;
inline bool ReconTaskParameterPB::_internal_has_task_name() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool ReconTaskParameterPB::has_task_name() const {
  return _internal_has_task_name();
}
inline void ReconTaskParameterPB::clear_task_name() {
  task_name_.ClearToEmpty();
  _has_bits_[0] &= ~0x00000001u;
}
inline const std::string& ReconTaskParameterPB::task_name() const {
  // @@protoc_insertion_point(field_get:recontaskparameter_pb.ReconTaskParameterPB.task_name)
  return _internal_task_name();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void ReconTaskParameterPB::set_task_name(ArgT0&& arg0, ArgT... args) {
 _has_bits_[0] |= 0x00000001u;
 task_name_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:recontaskparameter_pb.ReconTaskParameterPB.task_name)
}
inline std::string* ReconTaskParameterPB::mutable_task_name() {
  // @@protoc_insertion_point(field_mutable:recontaskparameter_pb.ReconTaskParameterPB.task_name)
  return _internal_mutable_task_name();
}
inline const std::string& ReconTaskParameterPB::_internal_task_name() const {
  return task_name_.Get();
}
inline void ReconTaskParameterPB::_internal_set_task_name(const std::string& value) {
  _has_bits_[0] |= 0x00000001u;
  task_name_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* ReconTaskParameterPB::_internal_mutable_task_name() {
  _has_bits_[0] |= 0x00000001u;
  return task_name_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* ReconTaskParameterPB::release_task_name() {
  // @@protoc_insertion_point(field_release:recontaskparameter_pb.ReconTaskParameterPB.task_name)
  if (!_internal_has_task_name()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000001u;
  return task_name_.ReleaseNonDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void ReconTaskParameterPB::set_allocated_task_name(std::string* task_name) {
  if (task_name != nullptr) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  task_name_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), task_name,
      GetArenaForAllocation());
  // @@protoc_insertion_point(field_set_allocated:recontaskparameter_pb.ReconTaskParameterPB.task_name)
}

// required string path_sysmat = 2;
inline bool ReconTaskParameterPB::_internal_has_path_sysmat() const {
  bool value = (_has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool ReconTaskParameterPB::has_path_sysmat() const {
  return _internal_has_path_sysmat();
}
inline void ReconTaskParameterPB::clear_path_sysmat() {
  path_sysmat_.ClearToEmpty();
  _has_bits_[0] &= ~0x00000002u;
}
inline const std::string& ReconTaskParameterPB::path_sysmat() const {
  // @@protoc_insertion_point(field_get:recontaskparameter_pb.ReconTaskParameterPB.path_sysmat)
  return _internal_path_sysmat();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void ReconTaskParameterPB::set_path_sysmat(ArgT0&& arg0, ArgT... args) {
 _has_bits_[0] |= 0x00000002u;
 path_sysmat_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:recontaskparameter_pb.ReconTaskParameterPB.path_sysmat)
}
inline std::string* ReconTaskParameterPB::mutable_path_sysmat() {
  // @@protoc_insertion_point(field_mutable:recontaskparameter_pb.ReconTaskParameterPB.path_sysmat)
  return _internal_mutable_path_sysmat();
}
inline const std::string& ReconTaskParameterPB::_internal_path_sysmat() const {
  return path_sysmat_.Get();
}
inline void ReconTaskParameterPB::_internal_set_path_sysmat(const std::string& value) {
  _has_bits_[0] |= 0x00000002u;
  path_sysmat_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* ReconTaskParameterPB::_internal_mutable_path_sysmat() {
  _has_bits_[0] |= 0x00000002u;
  return path_sysmat_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* ReconTaskParameterPB::release_path_sysmat() {
  // @@protoc_insertion_point(field_release:recontaskparameter_pb.ReconTaskParameterPB.path_sysmat)
  if (!_internal_has_path_sysmat()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000002u;
  return path_sysmat_.ReleaseNonDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void ReconTaskParameterPB::set_allocated_path_sysmat(std::string* path_sysmat) {
  if (path_sysmat != nullptr) {
    _has_bits_[0] |= 0x00000002u;
  } else {
    _has_bits_[0] &= ~0x00000002u;
  }
  path_sysmat_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), path_sysmat,
      GetArenaForAllocation());
  // @@protoc_insertion_point(field_set_allocated:recontaskparameter_pb.ReconTaskParameterPB.path_sysmat)
}

// required string path_sinogdram = 3;
inline bool ReconTaskParameterPB::_internal_has_path_sinogdram() const {
  bool value = (_has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline bool ReconTaskParameterPB::has_path_sinogdram() const {
  return _internal_has_path_sinogdram();
}
inline void ReconTaskParameterPB::clear_path_sinogdram() {
  path_sinogdram_.ClearToEmpty();
  _has_bits_[0] &= ~0x00000004u;
}
inline const std::string& ReconTaskParameterPB::path_sinogdram() const {
  // @@protoc_insertion_point(field_get:recontaskparameter_pb.ReconTaskParameterPB.path_sinogdram)
  return _internal_path_sinogdram();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void ReconTaskParameterPB::set_path_sinogdram(ArgT0&& arg0, ArgT... args) {
 _has_bits_[0] |= 0x00000004u;
 path_sinogdram_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:recontaskparameter_pb.ReconTaskParameterPB.path_sinogdram)
}
inline std::string* ReconTaskParameterPB::mutable_path_sinogdram() {
  // @@protoc_insertion_point(field_mutable:recontaskparameter_pb.ReconTaskParameterPB.path_sinogdram)
  return _internal_mutable_path_sinogdram();
}
inline const std::string& ReconTaskParameterPB::_internal_path_sinogdram() const {
  return path_sinogdram_.Get();
}
inline void ReconTaskParameterPB::_internal_set_path_sinogdram(const std::string& value) {
  _has_bits_[0] |= 0x00000004u;
  path_sinogdram_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* ReconTaskParameterPB::_internal_mutable_path_sinogdram() {
  _has_bits_[0] |= 0x00000004u;
  return path_sinogdram_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* ReconTaskParameterPB::release_path_sinogdram() {
  // @@protoc_insertion_point(field_release:recontaskparameter_pb.ReconTaskParameterPB.path_sinogdram)
  if (!_internal_has_path_sinogdram()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000004u;
  return path_sinogdram_.ReleaseNonDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void ReconTaskParameterPB::set_allocated_path_sinogdram(std::string* path_sinogdram) {
  if (path_sinogdram != nullptr) {
    _has_bits_[0] |= 0x00000004u;
  } else {
    _has_bits_[0] &= ~0x00000004u;
  }
  path_sinogdram_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), path_sinogdram,
      GetArenaForAllocation());
  // @@protoc_insertion_point(field_set_allocated:recontaskparameter_pb.ReconTaskParameterPB.path_sinogdram)
}

// optional string path_scatter_map = 4;
inline bool ReconTaskParameterPB::_internal_has_path_scatter_map() const {
  bool value = (_has_bits_[0] & 0x00000008u) != 0;
  return value;
}
inline bool ReconTaskParameterPB::has_path_scatter_map() const {
  return _internal_has_path_scatter_map();
}
inline void ReconTaskParameterPB::clear_path_scatter_map() {
  path_scatter_map_.ClearToEmpty();
  _has_bits_[0] &= ~0x00000008u;
}
inline const std::string& ReconTaskParameterPB::path_scatter_map() const {
  // @@protoc_insertion_point(field_get:recontaskparameter_pb.ReconTaskParameterPB.path_scatter_map)
  return _internal_path_scatter_map();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void ReconTaskParameterPB::set_path_scatter_map(ArgT0&& arg0, ArgT... args) {
 _has_bits_[0] |= 0x00000008u;
 path_scatter_map_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:recontaskparameter_pb.ReconTaskParameterPB.path_scatter_map)
}
inline std::string* ReconTaskParameterPB::mutable_path_scatter_map() {
  // @@protoc_insertion_point(field_mutable:recontaskparameter_pb.ReconTaskParameterPB.path_scatter_map)
  return _internal_mutable_path_scatter_map();
}
inline const std::string& ReconTaskParameterPB::_internal_path_scatter_map() const {
  return path_scatter_map_.Get();
}
inline void ReconTaskParameterPB::_internal_set_path_scatter_map(const std::string& value) {
  _has_bits_[0] |= 0x00000008u;
  path_scatter_map_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* ReconTaskParameterPB::_internal_mutable_path_scatter_map() {
  _has_bits_[0] |= 0x00000008u;
  return path_scatter_map_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* ReconTaskParameterPB::release_path_scatter_map() {
  // @@protoc_insertion_point(field_release:recontaskparameter_pb.ReconTaskParameterPB.path_scatter_map)
  if (!_internal_has_path_scatter_map()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000008u;
  return path_scatter_map_.ReleaseNonDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void ReconTaskParameterPB::set_allocated_path_scatter_map(std::string* path_scatter_map) {
  if (path_scatter_map != nullptr) {
    _has_bits_[0] |= 0x00000008u;
  } else {
    _has_bits_[0] &= ~0x00000008u;
  }
  path_scatter_map_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), path_scatter_map,
      GetArenaForAllocation());
  // @@protoc_insertion_point(field_set_allocated:recontaskparameter_pb.ReconTaskParameterPB.path_scatter_map)
}

// optional string path_mu_map = 5;
inline bool ReconTaskParameterPB::_internal_has_path_mu_map() const {
  bool value = (_has_bits_[0] & 0x00000010u) != 0;
  return value;
}
inline bool ReconTaskParameterPB::has_path_mu_map() const {
  return _internal_has_path_mu_map();
}
inline void ReconTaskParameterPB::clear_path_mu_map() {
  path_mu_map_.ClearToEmpty();
  _has_bits_[0] &= ~0x00000010u;
}
inline const std::string& ReconTaskParameterPB::path_mu_map() const {
  // @@protoc_insertion_point(field_get:recontaskparameter_pb.ReconTaskParameterPB.path_mu_map)
  return _internal_path_mu_map();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void ReconTaskParameterPB::set_path_mu_map(ArgT0&& arg0, ArgT... args) {
 _has_bits_[0] |= 0x00000010u;
 path_mu_map_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:recontaskparameter_pb.ReconTaskParameterPB.path_mu_map)
}
inline std::string* ReconTaskParameterPB::mutable_path_mu_map() {
  // @@protoc_insertion_point(field_mutable:recontaskparameter_pb.ReconTaskParameterPB.path_mu_map)
  return _internal_mutable_path_mu_map();
}
inline const std::string& ReconTaskParameterPB::_internal_path_mu_map() const {
  return path_mu_map_.Get();
}
inline void ReconTaskParameterPB::_internal_set_path_mu_map(const std::string& value) {
  _has_bits_[0] |= 0x00000010u;
  path_mu_map_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* ReconTaskParameterPB::_internal_mutable_path_mu_map() {
  _has_bits_[0] |= 0x00000010u;
  return path_mu_map_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* ReconTaskParameterPB::release_path_mu_map() {
  // @@protoc_insertion_point(field_release:recontaskparameter_pb.ReconTaskParameterPB.path_mu_map)
  if (!_internal_has_path_mu_map()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000010u;
  return path_mu_map_.ReleaseNonDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void ReconTaskParameterPB::set_allocated_path_mu_map(std::string* path_mu_map) {
  if (path_mu_map != nullptr) {
    _has_bits_[0] |= 0x00000010u;
  } else {
    _has_bits_[0] &= ~0x00000010u;
  }
  path_mu_map_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), path_mu_map,
      GetArenaForAllocation());
  // @@protoc_insertion_point(field_set_allocated:recontaskparameter_pb.ReconTaskParameterPB.path_mu_map)
}

// required bool use_nn = 6;
inline bool ReconTaskParameterPB::_internal_has_use_nn() const {
  bool value = (_has_bits_[0] & 0x00000040u) != 0;
  return value;
}
inline bool ReconTaskParameterPB::has_use_nn() const {
  return _internal_has_use_nn();
}
inline void ReconTaskParameterPB::clear_use_nn() {
  use_nn_ = false;
  _has_bits_[0] &= ~0x00000040u;
}
inline bool ReconTaskParameterPB::_internal_use_nn() const {
  return use_nn_;
}
inline bool ReconTaskParameterPB::use_nn() const {
  // @@protoc_insertion_point(field_get:recontaskparameter_pb.ReconTaskParameterPB.use_nn)
  return _internal_use_nn();
}
inline void ReconTaskParameterPB::_internal_set_use_nn(bool value) {
  _has_bits_[0] |= 0x00000040u;
  use_nn_ = value;
}
inline void ReconTaskParameterPB::set_use_nn(bool value) {
  _internal_set_use_nn(value);
  // @@protoc_insertion_point(field_set:recontaskparameter_pb.ReconTaskParameterPB.use_nn)
}

// required bool use_scatter_map = 7;
inline bool ReconTaskParameterPB::_internal_has_use_scatter_map() const {
  bool value = (_has_bits_[0] & 0x00000080u) != 0;
  return value;
}
inline bool ReconTaskParameterPB::has_use_scatter_map() const {
  return _internal_has_use_scatter_map();
}
inline void ReconTaskParameterPB::clear_use_scatter_map() {
  use_scatter_map_ = false;
  _has_bits_[0] &= ~0x00000080u;
}
inline bool ReconTaskParameterPB::_internal_use_scatter_map() const {
  return use_scatter_map_;
}
inline bool ReconTaskParameterPB::use_scatter_map() const {
  // @@protoc_insertion_point(field_get:recontaskparameter_pb.ReconTaskParameterPB.use_scatter_map)
  return _internal_use_scatter_map();
}
inline void ReconTaskParameterPB::_internal_set_use_scatter_map(bool value) {
  _has_bits_[0] |= 0x00000080u;
  use_scatter_map_ = value;
}
inline void ReconTaskParameterPB::set_use_scatter_map(bool value) {
  _internal_set_use_scatter_map(value);
  // @@protoc_insertion_point(field_set:recontaskparameter_pb.ReconTaskParameterPB.use_scatter_map)
}

// required int32 num_iters = 8;
inline bool ReconTaskParameterPB::_internal_has_num_iters() const {
  bool value = (_has_bits_[0] & 0x00000100u) != 0;
  return value;
}
inline bool ReconTaskParameterPB::has_num_iters() const {
  return _internal_has_num_iters();
}
inline void ReconTaskParameterPB::clear_num_iters() {
  num_iters_ = 0;
  _has_bits_[0] &= ~0x00000100u;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 ReconTaskParameterPB::_internal_num_iters() const {
  return num_iters_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 ReconTaskParameterPB::num_iters() const {
  // @@protoc_insertion_point(field_get:recontaskparameter_pb.ReconTaskParameterPB.num_iters)
  return _internal_num_iters();
}
inline void ReconTaskParameterPB::_internal_set_num_iters(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _has_bits_[0] |= 0x00000100u;
  num_iters_ = value;
}
inline void ReconTaskParameterPB::set_num_iters(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_num_iters(value);
  // @@protoc_insertion_point(field_set:recontaskparameter_pb.ReconTaskParameterPB.num_iters)
}

// required int32 num_dual_iters = 9;
inline bool ReconTaskParameterPB::_internal_has_num_dual_iters() const {
  bool value = (_has_bits_[0] & 0x00000800u) != 0;
  return value;
}
inline bool ReconTaskParameterPB::has_num_dual_iters() const {
  return _internal_has_num_dual_iters();
}
inline void ReconTaskParameterPB::clear_num_dual_iters() {
  num_dual_iters_ = 0;
  _has_bits_[0] &= ~0x00000800u;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 ReconTaskParameterPB::_internal_num_dual_iters() const {
  return num_dual_iters_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 ReconTaskParameterPB::num_dual_iters() const {
  // @@protoc_insertion_point(field_get:recontaskparameter_pb.ReconTaskParameterPB.num_dual_iters)
  return _internal_num_dual_iters();
}
inline void ReconTaskParameterPB::_internal_set_num_dual_iters(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _has_bits_[0] |= 0x00000800u;
  num_dual_iters_ = value;
}
inline void ReconTaskParameterPB::set_num_dual_iters(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_num_dual_iters(value);
  // @@protoc_insertion_point(field_set:recontaskparameter_pb.ReconTaskParameterPB.num_dual_iters)
}

// required double gamma = 10;
inline bool ReconTaskParameterPB::_internal_has_gamma() const {
  bool value = (_has_bits_[0] & 0x00000200u) != 0;
  return value;
}
inline bool ReconTaskParameterPB::has_gamma() const {
  return _internal_has_gamma();
}
inline void ReconTaskParameterPB::clear_gamma() {
  gamma_ = 0;
  _has_bits_[0] &= ~0x00000200u;
}
inline double ReconTaskParameterPB::_internal_gamma() const {
  return gamma_;
}
inline double ReconTaskParameterPB::gamma() const {
  // @@protoc_insertion_point(field_get:recontaskparameter_pb.ReconTaskParameterPB.gamma)
  return _internal_gamma();
}
inline void ReconTaskParameterPB::_internal_set_gamma(double value) {
  _has_bits_[0] |= 0x00000200u;
  gamma_ = value;
}
inline void ReconTaskParameterPB::set_gamma(double value) {
  _internal_set_gamma(value);
  // @@protoc_insertion_point(field_set:recontaskparameter_pb.ReconTaskParameterPB.gamma)
}

// required double lambda = 11;
inline bool ReconTaskParameterPB::_internal_has_lambda() const {
  bool value = (_has_bits_[0] & 0x00000400u) != 0;
  return value;
}
inline bool ReconTaskParameterPB::has_lambda() const {
  return _internal_has_lambda();
}
inline void ReconTaskParameterPB::clear_lambda() {
  lambda_ = 0;
  _has_bits_[0] &= ~0x00000400u;
}
inline double ReconTaskParameterPB::_internal_lambda() const {
  return lambda_;
}
inline double ReconTaskParameterPB::lambda() const {
  // @@protoc_insertion_point(field_get:recontaskparameter_pb.ReconTaskParameterPB.lambda)
  return _internal_lambda();
}
inline void ReconTaskParameterPB::_internal_set_lambda(double value) {
  _has_bits_[0] |= 0x00000400u;
  lambda_ = value;
}
inline void ReconTaskParameterPB::set_lambda(double value) {
  _internal_set_lambda(value);
  // @@protoc_insertion_point(field_set:recontaskparameter_pb.ReconTaskParameterPB.lambda)
}

// optional double scatter_coeff = 12;
inline bool ReconTaskParameterPB::_internal_has_scatter_coeff() const {
  bool value = (_has_bits_[0] & 0x00002000u) != 0;
  return value;
}
inline bool ReconTaskParameterPB::has_scatter_coeff() const {
  return _internal_has_scatter_coeff();
}
inline void ReconTaskParameterPB::clear_scatter_coeff() {
  scatter_coeff_ = 0;
  _has_bits_[0] &= ~0x00002000u;
}
inline double ReconTaskParameterPB::_internal_scatter_coeff() const {
  return scatter_coeff_;
}
inline double ReconTaskParameterPB::scatter_coeff() const {
  // @@protoc_insertion_point(field_get:recontaskparameter_pb.ReconTaskParameterPB.scatter_coeff)
  return _internal_scatter_coeff();
}
inline void ReconTaskParameterPB::_internal_set_scatter_coeff(double value) {
  _has_bits_[0] |= 0x00002000u;
  scatter_coeff_ = value;
}
inline void ReconTaskParameterPB::set_scatter_coeff(double value) {
  _internal_set_scatter_coeff(value);
  // @@protoc_insertion_point(field_set:recontaskparameter_pb.ReconTaskParameterPB.scatter_coeff)
}

// required string output_dir = 13;
inline bool ReconTaskParameterPB::_internal_has_output_dir() const {
  bool value = (_has_bits_[0] & 0x00000020u) != 0;
  return value;
}
inline bool ReconTaskParameterPB::has_output_dir() const {
  return _internal_has_output_dir();
}
inline void ReconTaskParameterPB::clear_output_dir() {
  output_dir_.ClearToEmpty();
  _has_bits_[0] &= ~0x00000020u;
}
inline const std::string& ReconTaskParameterPB::output_dir() const {
  // @@protoc_insertion_point(field_get:recontaskparameter_pb.ReconTaskParameterPB.output_dir)
  return _internal_output_dir();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void ReconTaskParameterPB::set_output_dir(ArgT0&& arg0, ArgT... args) {
 _has_bits_[0] |= 0x00000020u;
 output_dir_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:recontaskparameter_pb.ReconTaskParameterPB.output_dir)
}
inline std::string* ReconTaskParameterPB::mutable_output_dir() {
  // @@protoc_insertion_point(field_mutable:recontaskparameter_pb.ReconTaskParameterPB.output_dir)
  return _internal_mutable_output_dir();
}
inline const std::string& ReconTaskParameterPB::_internal_output_dir() const {
  return output_dir_.Get();
}
inline void ReconTaskParameterPB::_internal_set_output_dir(const std::string& value) {
  _has_bits_[0] |= 0x00000020u;
  output_dir_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* ReconTaskParameterPB::_internal_mutable_output_dir() {
  _has_bits_[0] |= 0x00000020u;
  return output_dir_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* ReconTaskParameterPB::release_output_dir() {
  // @@protoc_insertion_point(field_release:recontaskparameter_pb.ReconTaskParameterPB.output_dir)
  if (!_internal_has_output_dir()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000020u;
  return output_dir_.ReleaseNonDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void ReconTaskParameterPB::set_allocated_output_dir(std::string* output_dir) {
  if (output_dir != nullptr) {
    _has_bits_[0] |= 0x00000020u;
  } else {
    _has_bits_[0] &= ~0x00000020u;
  }
  output_dir_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), output_dir,
      GetArenaForAllocation());
  // @@protoc_insertion_point(field_set_allocated:recontaskparameter_pb.ReconTaskParameterPB.output_dir)
}

// required .recontaskparameter_pb.ReconTaskParameterPB.IteratorType iterator = 14;
inline bool ReconTaskParameterPB::_internal_has_iterator() const {
  bool value = (_has_bits_[0] & 0x00001000u) != 0;
  return value;
}
inline bool ReconTaskParameterPB::has_iterator() const {
  return _internal_has_iterator();
}
inline void ReconTaskParameterPB::clear_iterator() {
  iterator_ = 0;
  _has_bits_[0] &= ~0x00001000u;
}
inline ::recontaskparameter_pb::ReconTaskParameterPB_IteratorType ReconTaskParameterPB::_internal_iterator() const {
  return static_cast< ::recontaskparameter_pb::ReconTaskParameterPB_IteratorType >(iterator_);
}
inline ::recontaskparameter_pb::ReconTaskParameterPB_IteratorType ReconTaskParameterPB::iterator() const {
  // @@protoc_insertion_point(field_get:recontaskparameter_pb.ReconTaskParameterPB.iterator)
  return _internal_iterator();
}
inline void ReconTaskParameterPB::_internal_set_iterator(::recontaskparameter_pb::ReconTaskParameterPB_IteratorType value) {
  assert(::recontaskparameter_pb::ReconTaskParameterPB_IteratorType_IsValid(value));
  _has_bits_[0] |= 0x00001000u;
  iterator_ = value;
}
inline void ReconTaskParameterPB::set_iterator(::recontaskparameter_pb::ReconTaskParameterPB_IteratorType value) {
  _internal_set_iterator(value);
  // @@protoc_insertion_point(field_set:recontaskparameter_pb.ReconTaskParameterPB.iterator)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace recontaskparameter_pb

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::recontaskparameter_pb::ReconTaskParameterPB_IteratorType> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::recontaskparameter_pb::ReconTaskParameterPB_IteratorType>() {
  return ::recontaskparameter_pb::ReconTaskParameterPB_IteratorType_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_recontaskparameter_2eproto
